<?php

/**
 * Основной конфиг EE_FrameWork.
 * В этом файле должны находиться только настраиваемые параметры проекта.
 * Любая runtime-логика, вычисления и побочные эффекты выполняются в inc/bootstrap.php.
 */

return [
    'ENV_VERSION_CORE' => '1.0.0',

    // Настройка базы данных
    'ENV_DB_HOST' => 'localhost',
    'ENV_DB_USER' => 'db_user',
    'ENV_DB_PASS' => 'change_me',
    'ENV_DB_NAME' => 'ee_framework',
    'ENV_DB_PREF' => 'ee_',

    // Технические настройки сайта
    'ENV_SITE_NAME' => 'EE_FrameWork',
    'ENV_SITE_DESCRIPTION' => 'EE_FrameWork project',
    'ENV_SITE_AUTHOR' => 'EE_FrameWork',
    'ENV_GET_KEYWORDS' => 0,
    'ENV_DATE_SITE_CREATE' => '28.03.2026',
    'ENV_DIRSEP' => DIRECTORY_SEPARATOR,
    'ENV_CANONICAL_HOST' => 'example.local',
    'ENV_CANONICAL_SCHEME' => 'https',
    'ENV_CANONICAL_REDIRECT' => 1,
    'ENV_SITE_PATH' => realpath(dirname(__FILE__) . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR,
    'ENV_LOG' => 1,
    'ENV_LOG_RETENTION_DAYS' => 30,
    'ENV_LOG_ROTATE_FILE_SIZE' => 10 * 1024 * 1024,
    'ENV_LOG_MAX_BACKUPS' => 5,
    'ENV_LOG_REQUEST_ID_HEADER' => 'X-Request-Id',
    'ENV_BACKUP_RETENTION_DAYS' => 14,
    'ENV_BACKUP_MAX_LOCAL_SNAPSHOTS' => 20,
    'ENV_MEMORY_LIMIT_WEB' => '256M',
    'ENV_MEMORY_LIMIT_CLI' => '384M',
    'ENV_MEMORY_SOFT_LIMIT_MB' => 224,
    'ENV_CRON_MEMORY_SOFT_LIMIT_MB' => 256,
    'ENV_CRON_AGENT_MEMORY_SOFT_LIMIT_MB' => 224,
    'ENV_MEDIA_MIRROR_MEMORY_SOFT_LIMIT_MB' => 192,
    'ENV_CRON_TICK_TIME_BUDGET_SEC' => 45,
    'ENV_MEDIA_MIRROR_TIME_BUDGET_SEC' => 40,
	'ENV_IMPORT_CREATE_LEGACY_MEDIA_ALIASES' => 0,
    'ENV_COMPRESS_HTML' => 0,
	'ENV_SHOW_SIDENAV_FOOTER' => 1,
    'ENV_CREATE_WEBP' => true,
    'ENV_WEBP_QUALITY' => 80,
    'ENV_CACHE' => 0,
    'ENV_CACHE_LIFETIME' => 3600,
    'ENV_SECRET_KEY' => 'change-this-secret-key',
    'ENV_SITE' => 1,
    'ENV_TEST' => 0,
    'ENV_FATAL_ERROR_LOGGING' => 1,
    'ENV_CONFIRM_EMAIL' => 1,
    'ENV_TIME_AUTH_SESSION' => 86400 * 15,
    'ENV_TIME_ACTIVATION' => 86400 * 15,
    'ENV_SITE_INDEX' => 'noindex, nofollow',
    'ENV_FONT_AWESOME_CDN' => true,
    'ENV_BOOTSTRAP533_CDN' => true,
    'ENV_JQUERY_CDN' => true,
    'ENV_CACHE_REDIS' => 0,
    'ENV_CACHE_BACKEND' => 'file',
    'ENV_CACHE_NAMESPACE' => '',
    'ENV_CACHE_VERSION' => '',
    'ENV_GUARD_REDIS' => 0,
    'ENV_GUARD_RATE_LIMIT_COUNT' => 30,
    'ENV_GUARD_RATE_LIMIT_WINDOW' => 30,
    'ENV_GUARD_RATE_LIMIT_GET_COUNT' => 60,
    'ENV_GUARD_RATE_LIMIT_GET_WINDOW' => 30,
    'ENV_GUARD_RATE_LIMIT_WRITE_COUNT' => 15,
    'ENV_GUARD_RATE_LIMIT_WRITE_WINDOW' => 30,
    'ENV_GUARD_STRIKE_LIMIT' => 5,
    'ENV_GUARD_STRIKE_TTL' => 30,
    'ENV_REDIS_ADDRESS' => '127.0.0.1',
    'ENV_REDIS_PORT' => 6379,
    'ENV_REDIS_CONNECTION_CACHE_TTL' => 300,
    'ENV_MAX_FILE_SIZE' => 1000 * 1024 * 1024,
    'ENV_ROUTING_CACHE_ENABLED' => 0,
    'ENV_ROUTING_CACHE_BACKEND' => 'file',
    // Персональные настройки сайта
    'ENV_APP_DIRECTORY' => 'app',
    'ENV_PATH_LANG' => 'inc' . DIRECTORY_SEPARATOR . 'langs' . DIRECTORY_SEPARATOR,
    'ENV_PROTO_LANGUAGE' => 'EN',
    'ENV_CONTENT_LANGS' => ['EN'],
    'ENV_SITE_EMAIL' => 'admin@example.local',
    'ENV_ADMIN_EMAIL' => 'admin@example.local',
    'ENV_SUPPORT_EMAIL' => 'support@example.local',
    'ENV_LEGAL_OPERATOR_STATUS' => 'Укажите статус оператора',
    'ENV_LEGAL_OPERATOR_NAME' => 'Укажите наименование оператора',
    'ENV_LEGAL_OPERATOR_ADDRESS' => 'Укажите юридический адрес оператора',
    'ENV_LEGAL_OPERATOR_INN' => 'Укажите ИНН оператора',
    'ENV_LEGAL_OPERATOR_OGRN' => 'Укажите ОГРН/ОГРНИП оператора',
    'ENV_LEGAL_PRIVACY_POLICY_VERSION' => '2026-03-25',
    'ENV_LEGAL_PERSONAL_DATA_CONSENT_VERSION' => '2026-03-25',
    'ENV_INSTALL_ADMIN_PASSWORD' => '',
    'ENV_INSTALL_MODERATOR_PASSWORD' => '',
    'ENV_SMTP' => 0,
    'ENV_ONE_IP_ONE_USER' => 0,
    'ENV_AUTH_USER' => 2,
    'ENV_AUTH_TRANSPORT' => 'cookie',
    'ENV_AUTH_COOKIE_SAMESITE' => 'Lax',
    'ENV_AUTH_COOKIE_SECURE' => !empty($_SERVER['HTTPS']) && strtolower((string) $_SERVER['HTTPS']) !== 'off',
    'ENV_AUTH_TRUST_PROXY_HEADERS' => 0,
    'ENV_AUTH_TRUSTED_PROXIES' => ['127.0.0.1', '::1'],
    'ENV_AUTH_IP_RESTRICTED_ROLES' => [1, 2],
    'ENV_AUTH_GOOGLE_CLIENT_ID' => '',
    'ENV_AUTH_GOOGLE_CLIENT_SECRET' => '',
    'ENV_AUTH_GOOGLE_REDIRECT_URI' => '',
    'ENV_SMTP_PORT' => 465,
    'ENV_SMTP_SERVER' => '',
    'ENV_SMTP_LOGIN' => '',
    'ENV_SMTP_PASSWORD' => '',
];
