<?php

/**
 * Евгений Ефимченко, efimchenko.com
 * Содержит языковые строки для английской локализации интерфейса EE_FrameWork.
 * /inc/langs/EN.php
 */
$lang = [
    'sys.imports_profiles_list' => 'Import Profiles',
    'sys.imports_management' => 'Import Management',
    'sys.imports_new_profile_wp' => 'Create WordPress Profile',
    'sys.imports_description' => 'Here you can manage your saved import profiles.',
    'sys.imports_no_profiles' => 'No import profiles found yet.',
    'sys.imports_last_run' => 'Last Run',
    'sys.imports_type_db' => 'Type',
    'sys.imports_db_connection' => 'DB Connection',
    'sys.imports_adapter_file' => 'Adapter File',
    'sys.imports_edit_profile' => 'Edit Import Profile',
    'sys.imports_new_profile' => 'New Import Profile',
    'sys.imports_settings' => 'Settings',
    'sys.imports_profile_name' => 'Profile Name',
    'sys.imports_what_to_import' => 'What to Import',
    'sys.imports_core_content' => 'Core Content (Posts, Pages, Categories, Media)',
    'sys.imports_woo_data' => 'WooCommerce Data (Products, Orders)',
    'sys.imports_how_to_import' => 'Import Method',
    'sys.imports_db_host' => 'DB Host',
    'sys.imports_db_name' => 'DB Name',
    'sys.imports_db_user' => 'DB User',
    'sys.imports_db_pass' => 'DB Password',
    'sys.imports_db_pref' => 'Table Prefix',
    'sys.imports_adapter_path' => 'Path to Adapter File',
    'sys.imports_adapter_help' => 'Specify the full server path to the PHP file that will return the data array for import.',
    'sys.imports_sql_dump_path' => 'Path to .sql File',
    'sys.imports_run' => 'Run Import',
    'sys.imports_cron_run' => 'Run via CRON',
    'sys.imports_cron_help' => 'To run this profile automatically, use the command:',
    'sys.imports_log' => 'Execution Log',
    'sys.imports_sql_dump' => 'SQL Dump File',
    'sys.imports_sql_dump_help' => 'Upload a .sql, .gz, .gzip, or .zip file. A temporary DB will be created using the credentials (Host/User/Pass) specified above.',
    'sys.imports_temp_db_creds' => 'Credentials for Temp DB',
    'sys.imports_adapter_download' => 'Download ee_wp_exporter.php',
    'sys.imports_exporter_title' => 'WordPress Exporter Script',
    'sys.imports_exporter_help_1' => '1. Download exporter script.',
    'sys.imports_exporter_help_2' => '2. Upload it to WordPress root.',
    'sys.imports_exporter_help_3' => '3. Run it in browser, then upload generated package here.',
    'sys.imports_upload_package' => 'Upload JSON/JSONL package (.zip, .jsonl, .json)',
    'sys.imports_no_file_uploaded' => 'No package uploaded yet.',
    'sys.imports_file_limit' => 'Max upload size',
    'sys.save_settings' => 'Save settings',
    'sys.imports_test_mode' => 'Test Mode',
    'sys.imports_test_mode_enable' => 'Enable Test Mode',
    'sys.imports_test_mode_limit' => 'Import records limit:',
    'sys.imports_test_connection' => 'Test Connection',
    'sys.imports_err_posts_not_found' => 'Connection successful, but _posts table not found.',
    'sys.imports_ok_connection' => 'Success! Found prefix:',
    'sys.imports_saving' => 'Saving...',
    'sys.imports_running' => 'Running...',
    'sys.imports_done' => 'Done.',
    'sys.imports_error' => 'Error.',
    'sys.imports_delete_confirm' => 'Are you sure you want to delete this import profile? All associated files (dumps) and logs will also be deleted.',
    'sys.imports_sql_dump_help_v2' => 'Upload a .sql, .gz, .gzip, or .zip file. The import will use your website\'s current database connection settings.',
    'sys.imports_upload_new_dump' => 'Upload new dump file',
    'sys.imports_current_file' => 'Current file',
    'sys.imports_upload_adapter_file' => 'Upload .json/.zip file',
    'sys.imports_need_save' => 'File selected. Please save the profile to run the import.',
    'sys.imports_file_too_large' => 'The file might be too large.',   
];
$lang['sys.general'] = 'General';
$lang['sys.email'] = 'Email';
$lang['sys.your_email'] = 'Your email';
$lang['sys.test_email'] = 'Email for sending verification message';
$lang['sys.send_email'] = 'Send';
$lang['sys.password'] = 'Password';
$lang['sys.new_password'] = 'New Password';
$lang['sys.your_password'] = 'Your password';
$lang['sys.confirm_password'] = 'Confirm password';
$lang['sys.restore_password'] = 'Restore password';
$lang['sys.restore_password_process'] = 'Password recovery';
$lang['sys.log_in'] = 'Log In';
$lang['sys.log_out'] = 'Logout';
$lang['sys.sign_up'] = 'Sign Up';
$lang['sys.sign_up_text'] = 'Registration';
$lang['sys.welcome'] = 'Welcome';
$lang['sys.verify_email'] = 'We have sent a letter with a verification code to your email';
$lang['sys.new_password_in_email'] = 'We have sent you an email with a new password.';
$lang['sys.recovery_link_sent'] = 'We have sent a password recovery link to your email.';
$lang['sys.password_setup_link_sent'] = 'We have sent a password setup link to your email.';
$lang['sys.password_setup_mail_failed'] = 'Failed to send the password setup email.';
$lang['sys.password_setup'] = 'Password setup';
$lang['sys.password_setup_intro'] = 'Set a new password to continue using your account.';
$lang['sys.password_setup_completed'] = 'Password has been set successfully. You will be redirected now.';
$lang['sys.password_setup_reason'] = 'Password setup reason';
$lang['sys.password_too_short'] = 'Password must contain at least 5 characters.';
$lang['sys.password_changed_successfully'] = 'Password changed successfully. You will be redirected now.';
$lang['sys.set_new_password'] = 'Enter a new password to complete this action.';
$lang['sys.save_password'] = 'Save password';
$lang['sys.challenge_invalid'] = 'The link is invalid or has expired.';
$lang['sys.data_read_error'] = 'Data read error';
$lang['sys.data_being_saved'] = 'Please wait, the data is being saved';
$lang['sys.data_update_error'] = 'Data update error.';
$lang['sys.personal_data_updated'] = 'Personal settings have been updated';
$lang['sys.invalid_mail_format'] = 'Invalid email format.';
$lang['sys.no_connection_to_db'] = 'No connection to DB';
$lang['sys.db_registration_error'] = 'DB registration error';
$lang['sys.success'] = 'Success';
$lang['sys.the_mail_is_already_busy'] = 'The email is already taken';
$lang['sys.password_mismatch'] = 'Password mismatch';
$lang['sys.email_sending_error'] = 'Email sending error';
$lang['sys.successfully_activated'] = 'You have successfully activated your account and will be redirected.';
$lang['sys.activation_error'] = 'An activation error has occurred, the code has expired or does not exist. The data is cleared, please register again.';
$lang['sys.account_is_already_active'] = 'Your account is already activated.';
$lang['sys.you_were_blocked'] = 'We are sorry, but you were blocked, contact the site administrator.';
$lang['sys.account_deleted'] = 'This account has been deleted. Please contact the site administrator.';
$lang['sys.email_not_registered'] = 'Sorry, but you have not registered such email.';
$lang['sys.is_under_development'] = 'Sorry, but the functionality is under development.';
$lang['sys.no_such_data_was_found'] = 'No such user was found.';
$lang['sys.the_password_was_not_verified'] = 'The password is not correct.';
$lang['sys.you_have_not_verified_your_email'] = 'You have not verified your email.';
$lang['sys.account_is_blocked'] = 'Account is blocked.';
$lang['sys.unknown'] = 'Unknown';
$lang['sys.not_confirmed'] = 'Not verified';
$lang['sys.active'] = 'Аctive';
$lang['sys.hidden'] = 'Hidden';
$lang['sys.disabled'] = 'Disabled';
$lang['sys.blocked'] = 'Blocked';
$lang['sys.no_access'] = 'Access denied';
$lang['sys.no_data'] = 'No data';
$lang['sys.admin'] = 'Administrator';
$lang['sys.dashboard'] = 'Dashboard';
$lang['sys.dashboard_overview_heading'] = 'Project Overview';
$lang['sys.dashboard_overview_subtitle'] = 'Live snapshot of catalog, imports, agents, and operational state.';
$lang['sys.dashboard_operational_alerts'] = 'Operational Signals';
$lang['sys.dashboard_content_quality'] = 'Content Readiness';
$lang['sys.dashboard_readiness_percent'] = 'Ready for publish';
$lang['sys.dashboard_pages_active'] = 'Active';
$lang['sys.dashboard_pages_hidden'] = 'Hidden';
$lang['sys.dashboard_categories_with_photos'] = 'With gallery';
$lang['sys.dashboard_categories_with_map'] = 'With map';
$lang['sys.dashboard_owner_links'] = 'Owner links';
$lang['sys.dashboard_pages_without_owner'] = 'Without owner';
$lang['sys.dashboard_pages_without_contacts'] = 'Without contacts';
$lang['sys.dashboard_pages_without_photos'] = 'Without photos';
$lang['sys.dashboard_pages_without_rooms'] = 'Without room block';
$lang['sys.dashboard_contacts_verified'] = 'Contacts verified';
$lang['sys.dashboard_paid_placements'] = 'Paid placement';
$lang['sys.dashboard_placements_expiring'] = 'Expiring in 30 days';
$lang['sys.dashboard_recent_imports'] = 'Recent Imports';
$lang['sys.dashboard_recent_agent_runs'] = 'Recent Agent Runs';
$lang['sys.dashboard_recent_backups'] = 'Recent Backup Jobs';
$lang['sys.dashboard_no_imports'] = 'No import profiles have been run yet.';
$lang['sys.dashboard_no_runs'] = 'No agent runs yet.';
$lang['sys.dashboard_no_backup_jobs'] = 'No backup jobs have been run yet.';
$lang['sys.dashboard_admin_only'] = 'Detailed system overview is available to administrators.';
$lang['sys.dashboard_contacts_block'] = 'Contacts and photos';
$lang['sys.dashboard_room_block'] = 'Rooms and placement';
$lang['sys.name'] = 'Name';
$lang['sys.value'] = 'Value';
$lang['sys.description'] = 'Description';
$lang['sys.short_description'] = 'Short description';
$lang['sys.content'] = 'Content';
$lang['sys.phone'] = 'Phone';
$lang['sys.site'] = 'Website';
$lang['sys.status'] = 'Status';
$lang['sys.not_assigned'] = 'Not assigned';
$lang['sys.default'] = 'Default';
$lang['sys.optional'] = 'Optional';
$lang['sys.title'] = 'Title';
$lang['sys.enter_title'] = 'Enter the title';
$lang['sys.sort'] = 'Sorting';
$lang['sys.heading'] = 'Heading';
$lang['sys.date'] = 'Date';
$lang['sys.time'] = 'Time';
$lang['sys.edit'] = 'Edit';
$lang['sys.used'] = 'Used';
$lang['sys.delete'] = 'Delete';
$lang['sys.save'] = 'Save';
$lang['sys.delete_all'] = 'Delete everything';
$lang['sys.clear'] = 'Сlear';
$lang['sys.clear_file'] = 'Сlear file';
$lang['sys.file_name'] = 'File name';
$lang['sys.allowed_files'] = 'Allowed files';
$lang['sys.file_marked_for_delete'] = 'File will be deleted after saving the form';
$lang['sys.undo_delete'] = 'Undo deletion';
$lang['sys.file_unavailable'] = 'File unavailable';
$lang['sys.external_reference'] = 'External reference';
$lang['sys.legacy_reference'] = 'Legacy reference';
$lang['sys.apply_filters'] = 'Apply filters';
$lang['sys.activity'] = 'Activity';
$lang['sys.role'] = 'Role';
$lang['sys.roles'] = 'Roles';
$lang['sys.action'] = 'Action';
$lang['sys.actions'] = 'Actions';
$lang['sys.add'] = 'Add';
$lang['sys.ip'] = 'IP';
$lang['sys.last_ip'] = 'Last IP';
$lang['sys.registered_users'] = 'Registered users';
$lang['sys.user_info'] = 'User info';
$lang['sys.users'] = 'Users';
$lang['sys.deleted_users'] = 'Deleted';
$lang['sys.categories'] = 'Categories';
$lang['sys.category'] = 'Category';
$lang['sys.pages'] = 'Pages';
$lang['sys.page'] = 'Page';
$lang['sys.filters_management'] = 'Filters management';
$lang['sys.entities'] = 'Entities';
$lang['sys.entity'] = 'Entity';
$lang['sys.message'] = 'Message';
$lang['sys.messages'] = 'Messages';
$lang['sys.all'] = 'All';
$lang['sys.read'] = 'Read';
$lang['sys.mark_as_read'] = 'Mark as read';
$lang['sys.mark_everything_as_read'] = 'Mark everything as read';
$lang['sys.category_pages'] = 'Category pages';
$lang['sys.sets'] = 'Sets';
$lang['sys.set'] = 'Set';
$lang['sys.features'] = 'Features';
$lang['sys.type_categories'] = 'Category types';
$lang['sys.parent'] = 'Parent';
$lang['sys.author'] = 'Автор';
$lang['sys.type'] = 'Type';
$lang['sys.types'] = 'Types';
$lang['sys.scope'] = 'Scope';
$lang['sys.target'] = 'Target';
$lang['sys.property'] = 'Property';
$lang['sys.properties'] = 'Properties';
$lang['sys.property_sets'] = 'Property sets';
$lang['sys.property_lifecycle_jobs'] = 'Property lifecycle jobs';
$lang['sys.property_lifecycle_run_next'] = 'Run next queued job';
$lang['sys.date_create'] = 'Date of creation';
$lang['sys.date_update'] = 'Update date';
$lang['sys.created'] = 'Created';
$lang['sys.updated'] = 'Updated';
$lang['sys.progress'] = 'Progress';
$lang['sys.date_activity'] = 'Activity date';
$lang['sys.read_at'] = 'Date read';
$lang['sys.user_edit'] = 'Editing a user';
$lang['sys.categories_edit'] = 'Editing categories';
$lang['sys.comment'] = 'A comment';
$lang['sys.safety'] = 'Safety';
$lang['sys.basics'] = 'Basics';
$lang['sys.list'] = 'List';
$lang['sys.list_properties_for_set'] = 'List of properties for the set';
$lang['sys.select'] = 'Select';
$lang['sys.yes'] = 'Yes';
$lang['sys.no'] = 'No';
$lang['sys.fields'] = 'Fields';
$lang['sys.field_type'] = 'Field_type';
$lang['sys.field'] = 'Field';
$lang['sys.empty'] = 'Empty';
$lang['sys.separate_window'] = 'Separate window';
$lang['sys.multiple_choice'] = 'Multiple choice';
$lang['sys.required'] = 'Required';
$lang['sys.logs'] = 'Logs';
$lang['sys.php_logs'] = 'PHP logs';
$lang['sys.fatal_logs'] = 'Fatal logs';
$lang['sys.project_logs'] = 'Project logs';
$lang['sys.clear_html_cache'] = 'Clear HTML cache';
$lang['sys.clear_route_cache'] = 'Clear route cache';
$lang['sys.reset_redis_probe'] = 'Reset Redis probe';
$lang['sys.clear_php_logs'] = 'Clear PHP logs';
$lang['sys.clear_fatal_logs'] = 'Clear fatal logs';
$lang['sys.clear_project_logs'] = 'Clear project logs';
$lang['sys.cache_html_cleared'] = 'HTML cache has been cleared.';
$lang['sys.cache_route_cleared'] = 'Route cache has been cleared.';
$lang['sys.redis_probe_reset'] = 'Redis availability probe will be executed again.';
$lang['sys.cron_agents'] = 'Cron agents';
$lang['sys.cron_agent'] = 'Cron agent';
$lang['sys.cron_agent_runs'] = 'Cron agent run history';
$lang['sys.cron_agent_new'] = 'New cron agent';
$lang['sys.cron_agent_edit'] = 'Edit cron agent';
$lang['sys.cron_agent_saved'] = 'Cron agent saved.';
$lang['sys.cron_agent_deleted'] = 'Cron agent deleted.';
$lang['sys.cron_agent_not_found'] = 'Cron agent not found.';
$lang['sys.cron_agent_code'] = 'Code';
$lang['sys.cron_agent_handler'] = 'Handler';
$lang['sys.cron_agent_schedule_mode'] = 'Schedule mode';
$lang['sys.cron_agent_schedule_interval'] = 'Interval';
$lang['sys.cron_agent_schedule_cron'] = 'Cron expression';
$lang['sys.cron_agent_schedule_manual'] = 'Manual only';
$lang['sys.cron_agent_interval_minutes'] = 'Interval, minutes';
$lang['sys.cron_agent_cron_expression'] = 'Cron expression';
$lang['sys.cron_agent_payload_json'] = 'Payload JSON';
$lang['sys.cron_agent_payload_help'] = 'Store only handler parameters in payload. The handler code stays in the project files.';
$lang['sys.cron_agent_handler_settings'] = 'Handler settings';
$lang['sys.cron_agent_handler_settings_empty'] = 'This handler has no dedicated settings.';
$lang['sys.cron_agent_payload_batch_limit'] = 'Files per tick';
$lang['sys.cron_agent_payload_batch_limit_help'] = 'How many media queue items the worker should process in one scheduler run. Increase carefully to avoid server overload.';
$lang['sys.cron_agent_payload_media_retry_delay'] = 'Media retry delay, sec';
$lang['sys.cron_agent_payload_media_retry_delay_help'] = 'How long the media worker waits before retrying a failed file download from the queue.';
$lang['sys.cron_agent_payload_media_time_budget'] = 'Time budget, sec';
$lang['sys.cron_agent_payload_media_time_budget_help'] = 'How many seconds the media worker may process the queue in one run before it stops gracefully by guard limits.';
$lang['sys.cron_agent_payload_job_id'] = 'Import profile ID';
$lang['sys.cron_agent_payload_job_id_help'] = 'The import profile identifier that the import.profile handler should run.';
$lang['sys.cron_agent_payload_min_hits'] = 'Minimum hits';
$lang['sys.cron_agent_payload_min_hits_help'] = 'The minimum search-query hit count required before the popularity recalculation includes it.';
$lang['sys.cron_agent_payload_query_limit'] = 'Query limit';
$lang['sys.cron_agent_payload_query_limit_help'] = 'How many popular search queries to process per run.';
$lang['sys.cron_agent_payload_result_limit'] = 'Result limit';
$lang['sys.cron_agent_payload_result_limit_help'] = 'How many top results to boost for each popular query.';
$lang['sys.cron_agent_payload_decay_factor'] = 'Decay factor';
$lang['sys.cron_agent_payload_decay_factor_help'] = 'A value from 0 to 1. Lower values make accumulated popularity decay faster.';
$lang['sys.cron_agent_next_run'] = 'Next run';
$lang['sys.cron_agent_last_run'] = 'Last run';
$lang['sys.cron_agent_run_now'] = 'Run now';
$lang['sys.cron_agent_run_scheduler'] = 'Run scheduler';
$lang['sys.cron_agent_recover_stale'] = 'Recover stale cron agents';
$lang['sys.cron_agent_scheduler_help'] = 'Configure your system cron to run this script every minute:';
$lang['sys.cron_agent_scheduler_single_command'] = 'You only need to configure one minute-based scheduler command on the server:';
$lang['sys.cron_agent_bootstrap_notice'] = 'Required system cron agents are created automatically during platform deployment.';
$lang['sys.cron_agent_auto_created_list'] = 'System agents created automatically:';
$lang['sys.cron_agent_auto_created_hint'] = 'Required system agents are created automatically during deployment and the first application bootstrap.';
$lang['sys.cron_agent_status_due'] = 'Due';
$lang['sys.cron_agent_status_idle'] = 'Idle';
$lang['sys.cron_agent_status_cooldown'] = 'Cooldown';
$lang['sys.cron_agent_enable'] = 'Enable';
$lang['sys.cron_agent_disable'] = 'Disable';
$lang['sys.cron_agent_weight'] = 'Weight';
$lang['sys.cron_agent_max_runtime'] = 'Max runtime, sec';
$lang['sys.cron_agent_lock_ttl'] = 'Lock TTL, sec';
$lang['sys.cron_agent_retry_delay'] = 'Retry delay, sec';
$lang['sys.cron_agent_recent_runs'] = 'Recent runs';
$lang['sys.cron_agent_trigger_source'] = 'Trigger source';
$lang['sys.cron_agent_worker_id'] = 'Worker';
$lang['sys.cron_agent_duration_ms'] = 'Duration, ms';
$lang['sys.cron_agent_max_per_tick'] = 'Tasks per tick limit';
$lang['sys.cron_agent_max_weight'] = 'Load limit';
$lang['sys.cron_agent_max_concurrent'] = 'Concurrent tasks limit';
$lang['sys.cron_agent_runs_retention_notice'] = 'Run history is pruned automatically and does not grow forever.';
$lang['sys.cron_agent_runs_retention_current'] = 'Currently in DB:';
$lang['sys.cron_agent_runs_retention_policy'] = 'Retention policy:';
$lang['sys.cron_agent_runs_retention_days'] = 'days';
$lang['sys.cron_agent_runs_retention_rows'] = 'rows';
$lang['sys.cron_infrastructure'] = 'Cron infrastructure';
$lang['sys.cron_handler_property_lifecycle'] = 'Process lifecycle queue';
$lang['sys.cron_handler_property_lifecycle_desc'] = 'Runs the next queued property lifecycle job.';
$lang['sys.cron_handler_search_popularity'] = 'Update search popularity';
$lang['sys.cron_handler_search_popularity_desc'] = 'Recalculates search popularity boosts and applies score decay.';
$lang['sys.cron_handler_import_profile'] = 'Import profile';
$lang['sys.cron_handler_import_profile_desc'] = 'Runs an import profile using payload.job_id.';
$lang['sys.cron_handler_media_mirror'] = 'Background import media mirror';
$lang['sys.cron_handler_media_mirror_desc'] = 'Mirrors imported external images and files into local storage.';
$lang['sys.cron_handler_health_check'] = 'System health check';
$lang['sys.cron_handler_health_check_desc'] = 'Collects a consolidated system health report.';
$lang['sys.imports_cron_agent_title'] = 'Import profiles should preferably run through a cron agent';
$lang['sys.imports_cron_agent_desc'] = 'Create an agent with handler import.profile and a payload JSON containing job_id. The minute scheduler will then run the profile from the database schedule.';
$lang['sys.imports_cron_agent_create'] = 'Create a cron agent for this profile';
$lang['sys.imports_cron_agent_manual'] = 'A one-off manual run of this import profile is still available with the command:';
$lang['sys.imports_cron_agent_sync'] = 'Sync cron agent';
$lang['sys.imports_cron_agent_synced'] = 'The import profile cron agent has been synchronized.';
$lang['sys.imports_cron_agent_deleted'] = 'The import profile cron agent has been deleted.';
$lang['sys.imports_cron_agent_missing'] = 'No linked cron agent has been created yet.';
$lang['sys.health'] = 'System health';
$lang['sys.install'] = 'Installation';
$lang['sys.core_tables'] = 'Core tables';
$lang['sys.auth_infrastructure'] = 'Auth infrastructure';
$lang['sys.paths'] = 'Paths';
$lang['sys.path'] = 'Path';
$lang['sys.exists'] = 'Exists';
$lang['sys.writable'] = 'Writable';
$lang['sys.cache'] = 'Cache';
$lang['sys.route_cache'] = 'Route cache';
$lang['sys.queued'] = 'Queued';
$lang['sys.running'] = 'Running';
$lang['sys.failed'] = 'Failed';
$lang['sys.stale_jobs'] = 'Stale jobs';
$lang['sys.recover_stale_jobs'] = 'Recover stale jobs';
$lang['sys.recover_stale_operations'] = 'Recover stale operations';
$lang['sys.recover_stale_operations_done'] = 'Stale operations check has completed.';
$lang['sys.recover_stale_operations_failed'] = 'Failed to recover stale operations.';
$lang['sys.media_diagnostics'] = 'Media diagnostics';
$lang['sys.media_queue'] = 'Media queue';
$lang['sys.media_queue_pending'] = 'Pending';
$lang['sys.media_queue_running'] = 'Running';
$lang['sys.media_queue_failed'] = 'Failed';
$lang['sys.media_queue_terminal_failed'] = 'No retry';
$lang['sys.health_alerts'] = 'System alerts';
$lang['sys.health_alerts_summary'] = 'Critical:';
$lang['sys.health_alerts_warning'] = 'Warnings:';
$lang['sys.health_alerts_info'] = 'Info:';
$lang['sys.health_no_alerts'] = 'No critical or warning events were detected.';
$lang['sys.storage'] = 'Storage';
$lang['sys.disk_free'] = 'Free';
$lang['sys.disk_total'] = 'Total';
$lang['sys.disk_used_percent'] = 'Used';
$lang['sys.health_alert_db_down_title'] = 'Database is unavailable';
$lang['sys.health_alert_db_down_message'] = 'The application cannot connect to the database. Check MariaDB/MySQL and the server memory limits.';
$lang['sys.health_alert_core_tables_title'] = 'Core tables are not fully available';
$lang['sys.health_alert_core_tables_message'] = 'Some framework core tables are missing or unreadable.';
$lang['sys.health_alert_auth_tables_title'] = 'Auth infrastructure is incomplete';
$lang['sys.health_alert_auth_tables_message'] = 'Authentication tables are not fully available. Logins and sessions may work incorrectly.';
$lang['sys.health_alert_cron_tables_title'] = 'Cron infrastructure is incomplete';
$lang['sys.health_alert_cron_tables_message'] = 'Some scheduler tables are missing, so system agents cannot run normally.';
$lang['sys.health_alert_path_missing_title'] = 'A required path is missing';
$lang['sys.health_alert_path_missing_message'] = 'The required path {path_key} is missing: {path_value}';
$lang['sys.health_alert_path_unwritable_title'] = 'A required path is not writable';
$lang['sys.health_alert_path_unwritable_message'] = 'The required path {path_key} is not writable: {path_value}';
$lang['sys.health_alert_disk_critical_title'] = 'Disk space is critically low';
$lang['sys.health_alert_disk_critical_message'] = 'Only {free} of {total} is free ({used_percent}% used). Clean up or expand storage urgently.';
$lang['sys.health_alert_disk_warning_title'] = 'Disk free space is getting low';
$lang['sys.health_alert_disk_warning_message'] = 'There is {free} free of {total} ({used_percent}% used). Monitor growth of media, backups and logs.';
$lang['sys.health_alert_cron_stalled_title'] = 'The minute scheduler has stalled';
$lang['sys.health_alert_cron_stalled_message'] = 'The last cron run was {minutes} minutes ago or has never been recorded.';
$lang['sys.health_alert_cron_delayed_title'] = 'The minute scheduler is delayed';
$lang['sys.health_alert_cron_delayed_message'] = 'The last cron run was {minutes} minutes ago.';
$lang['sys.health_alert_cron_failed_title'] = 'Some cron agents currently have errors';
$lang['sys.health_alert_cron_failed_message'] = 'Cron agents whose latest state is failed: {count}.';
$lang['sys.health_alert_cron_stale_title'] = 'Stale cron agent locks were detected';
$lang['sys.health_alert_cron_stale_message'] = 'Stale-locked cron agents: {count}.';
$lang['sys.health_alert_lifecycle_stale_title'] = 'Stale lifecycle jobs were detected';
$lang['sys.health_alert_lifecycle_stale_message'] = 'Stale lifecycle jobs count: {count}.';
$lang['sys.health_alert_media_stale_title'] = 'Stale media queue items were detected';
$lang['sys.health_alert_media_stale_message'] = 'Stale media queue items count: {count}.';
$lang['sys.health_alert_media_failed_title'] = 'The media queue contains retryable failures';
$lang['sys.health_alert_media_failed_message'] = 'Media queue items in failed state: {count}.';
$lang['sys.health_alert_media_terminal_failed_title'] = 'The media queue contains permanently broken files';
$lang['sys.health_alert_media_terminal_failed_message'] = 'Media queue items with no more retries: {count}.';
$lang['sys.health_alert_media_pending_title'] = 'Background media mirroring is still in progress';
$lang['sys.health_alert_media_pending_message'] = 'There are still {count} items left in the queue. This is not an error, but the import is not fully finished yet.';
$lang['sys.health_alert_backup_stale_title'] = 'Stale backup jobs were detected';
$lang['sys.health_alert_backup_stale_message'] = 'Stale backup jobs count: {count}.';
$lang['sys.health_alert_backup_failed_title'] = 'There are backup jobs with errors';
$lang['sys.health_alert_backup_failed_message'] = 'Backup jobs in failed state: {count}.';
$lang['sys.health_alert_mail_transport_title'] = 'Mail transport is unavailable';
$lang['sys.health_alert_mail_transport_message'] = 'Mail mode {mode} is configured without a working transport ({transport}). Registration, recovery and system emails will be unreliable.';
$lang['sys.transport'] = 'Transport';
$lang['sys.confirm_email_required'] = 'Email confirmation';
$lang['sys.media_queue_done'] = 'Done';
$lang['sys.media_queue_last_completed'] = 'Last mirrored batch';
$lang['sys.media_queue_worker'] = 'System agent media-mirror-worker';
$lang['sys.media_queue_worker_notice'] = 'External media is picked up automatically by the built-in system agent created during installation.';
$lang['sys.media_queue_worker_save_quick'] = 'Save media-worker settings';
$lang['sys.media_queue_worker_settings_saved'] = 'Media-worker settings have been updated.';
$lang['sys.import_media_queue_notification'] = 'Import completed. Media has been queued for the system background worker (%d).';
$lang['sys.refresh_media_metadata'] = 'Refresh media metadata';
$lang['sys.referenced_files'] = 'Referenced files';
$lang['sys.unreferenced_files'] = 'Unreferenced files';
$lang['sys.missing_on_disk'] = 'Missing on disk';
$lang['sys.dangling_references'] = 'Dangling references';
$lang['sys.legacy_payloads'] = 'Legacy payloads';
$lang['sys.run_backup'] = 'Create backup';
$lang['sys.snapshots'] = 'Snapshots';
$lang['sys.total'] = 'Total';
$lang['sys.backup'] = 'Backup';
$lang['sys.backup_job_queued'] = 'Backup has been queued.';
$lang['sys.backup_job_queue_failed'] = 'Failed to queue the backup.';
$lang['sys.backup_jobs_queued'] = 'Queued';
$lang['sys.backup_jobs_running'] = 'Running';
$lang['sys.backup_jobs_done'] = 'Done';
$lang['sys.backup_jobs_partial'] = 'Partial';
$lang['sys.backup_jobs_failed'] = 'Failed';
$lang['sys.backup_scope'] = 'Backup contents';
$lang['sys.backup_scope_project_data'] = 'Database + project data';
$lang['sys.backup_scope_db_only'] = 'Database only';
$lang['sys.backup_scope_help'] = 'Project data includes custom/, uploads/, .htaccess and inc/configuration.php. Framework code is expected to come from git/releases.';
$lang['sys.backup_delivery_mode'] = 'Delivery mode';
$lang['sys.backup_delivery_local_only'] = 'Local only';
$lang['sys.backup_delivery_local_and_remote'] = 'Local and remote host';
$lang['sys.backup_delivery_remote_required'] = 'Remote host is required';
$lang['sys.backup_remote_target'] = 'Remote host';
$lang['sys.backup_remote_target_default'] = 'Use default target';
$lang['sys.backup_remote_target_help'] = 'For remote delivery you can select a specific target or rely on the default one.';
$lang['sys.backup_local_storage_notice'] = 'Local snapshots are pruned automatically by the retention policy.';
$lang['sys.backup_local_snapshots_limit'] = 'latest snapshots';
$lang['sys.backup_storage_summary'] = 'Local storage and worker';
$lang['sys.backup_default_remote_target'] = 'Default target';
$lang['sys.backup_recent_local_snapshots'] = 'Recent local snapshots';
$lang['sys.backup_recent_jobs'] = 'Recent backup jobs';
$lang['sys.backup_queue_run'] = 'Queue backup';
$lang['sys.backup_plans'] = 'Backup plans';
$lang['sys.backup_plan'] = 'Backup plan';
$lang['sys.backup_plan_new'] = 'New backup plan';
$lang['sys.backup_plan_edit'] = 'Edit backup plan';
$lang['sys.backup_plan_saved'] = 'Backup plan saved.';
$lang['sys.backup_plan_deleted'] = 'Backup plan deleted.';
$lang['sys.backup_plan_not_found'] = 'Backup plan not found.';
$lang['sys.backup_plan_code'] = 'Plan code';
$lang['sys.backup_plan_default'] = 'Default plan';
$lang['sys.backup_default_plan'] = 'Default plan';
$lang['sys.backup_plan_run_help'] = 'Launching a backup queues a job. Database tables, files and remote delivery are taken from the selected plan.';
$lang['sys.backup_database_contents'] = 'Database contents';
$lang['sys.backup_files_contents'] = 'Files contents';
$lang['sys.backup_mode_all_tables'] = 'All tables';
$lang['sys.backup_mode_only_selected_tables'] = 'Only selected tables';
$lang['sys.backup_mode_exclude_selected_tables'] = 'All tables except selected';
$lang['sys.backup_mode_no_database'] = 'No database';
$lang['sys.backup_mode_all_files'] = 'All available files and folders';
$lang['sys.backup_mode_only_selected_files'] = 'Only selected files and folders';
$lang['sys.backup_mode_exclude_selected_files'] = 'All files and folders except selected';
$lang['sys.backup_mode_no_files'] = 'No file payload';
$lang['sys.backup_tables_hint'] = 'The table list is used for the "only selected" and "except selected" modes.';
$lang['sys.backup_files_hint'] = 'Logs and cache can be excluded from a full snapshot plan, while uploads can be included or excluded explicitly.';
$lang['sys.backup_tables'] = 'Database tables';
$lang['sys.backup_files_and_folders'] = 'Files and folders';
$lang['sys.backup_scheduler_notice'] = 'Backups are processed by a background system agent.';
$lang['sys.backup_scheduler_command_help'] = 'The server must run a single minute scheduler command:';
$lang['sys.backup_run_worker_now'] = 'Run backup-worker';
$lang['sys.backup_remote_targets'] = 'Remote storage targets';
$lang['sys.backup_remote_targets_empty'] = 'No remote storage profiles are configured yet. Local backups already work without them.';
$lang['sys.backup_target_new'] = 'New remote storage profile';
$lang['sys.backup_target_edit'] = 'Edit remote storage profile';
$lang['sys.backup_target_not_found'] = 'Remote storage profile not found.';
$lang['sys.backup_target_saved'] = 'Remote storage profile saved.';
$lang['sys.backup_target_deleted'] = 'Remote storage profile deleted.';
$lang['sys.backup_target_default'] = 'Default';
$lang['sys.backup_target_test'] = 'Test connection';
$lang['sys.backup_target_test_success'] = 'Remote storage connection verified.';
$lang['sys.backup_target_test_failed'] = 'Remote storage connection test failed.';
$lang['sys.backup_target_code'] = 'Profile code';
$lang['sys.backup_target_remote_path'] = 'Remote path';
$lang['sys.backup_target_remote_path_help'] = 'The system creates a snapshot subdirectory under this path and uploads manifest/db/files archives there.';
$lang['sys.backup_target_ftp_passive'] = 'FTP passive mode';
$lang['sys.backup_target_password_keep'] = 'Leave empty to keep the current password';
$lang['sys.host'] = 'Host';
$lang['sys.port'] = 'Port';
$lang['sys.login'] = 'Login';
$lang['sys.timeout'] = 'Timeout';
$lang['sys.cron_handler_backup_worker'] = 'Background backup queue worker';
$lang['sys.cron_handler_backup_worker_desc'] = 'Processes queued backups, creates local snapshots and uploads them to remote hosts.';
$lang['sys.cron_agent_payload_backup_stale_after'] = 'Mark stale after, sec';
$lang['sys.cron_agent_payload_backup_stale_after_help'] = 'If a backup job stays in running for too long, the worker marks it failed and frees the queue.';
$lang['sys.fill_with_test_data'] = 'Fill with test data';
$lang['sys.delete_database_data'] = 'Delete database data';
$lang['sys.project_development'] = 'Project development';
$lang['sys.order_a_project'] = 'Order a project';
$lang['sys.review'] = 'Review';
$lang['sys.kill_db'] = 'All database tables will be deleted!';
$lang['sys.error_type'] = 'Error type';
$lang['sys.stack_trace'] = 'Stack trace';
$lang['sys.log_channel'] = 'Channel';
$lang['sys.log_channels'] = 'Channels';
$lang['sys.file_count'] = 'Files';
$lang['sys.archive_count'] = 'Archives';
$lang['sys.log_size'] = 'Size';
$lang['sys.last_update'] = 'Last update';
$lang['sys.level'] = 'Level';
$lang['sys.request_id'] = 'Request ID';
$lang['sys.request'] = 'Request';
$lang['sys.context'] = 'Context';
$lang['sys.meta'] = 'Meta';
$lang['sys.initiator'] = 'Initiator';
$lang['sys.result'] = 'Result';
$lang['sys.details'] = 'Details';
$lang['sys.subscribed'] = 'Subscribed';
$lang['sys.required_consents'] = 'Required consents';
$lang['sys.required_consents_title'] = 'Required documents';
$lang['sys.required_consents_intro'] = 'To continue using the platform, accept the two mandatory legal documents.';
$lang['sys.required_consents_missing'] = 'To continue, you must accept the Privacy Policy and the Personal Data Processing Consent.';
$lang['sys.privacy_policy'] = 'Privacy Policy';
$lang['sys.personal_data_consent'] = 'Personal Data Processing Consent';
$lang['sys.accept_privacy_policy'] = 'I have read and accept the Privacy Policy';
$lang['sys.accept_personal_data_consent'] = 'I consent to the processing of personal data';
$lang['sys.privacy_policy_acceptance_required'] = 'You must accept the Privacy Policy.';
$lang['sys.personal_data_consent_required'] = 'You must consent to the processing of personal data.';
$lang['sys.save_consents'] = 'Save consents';
$lang['sys.open_document'] = 'Open document';
$lang['sys.document_version'] = 'Document version';
$lang['sys.accepted_at'] = 'Accepted';
$lang['sys.provider_consent_title'] = 'Confirm required documents';
$lang['sys.provider_consent_intro'] = 'Before continuing with an external provider, confirm the mandatory legal documents of the platform.';
$lang['sys.continue'] = 'Continue';
$lang['sys.filtres'] = 'Filtres';
$lang['sys.database'] = 'DataBase';
$lang['sys.copy'] = 'Copy';
$lang['sys.insert'] = 'Insert';
$lang['sys.cancel'] = 'Cancel';
$lang['sys.close'] = 'Сlose';
$lang['sys.download'] = 'Download';
$lang['sys.authorization'] = 'Authorization';
$lang['sys.continue_with_google'] = 'Continue with Google';
$lang['sys.provider_not_configured'] = 'The selected auth provider is not configured yet.';
$lang['sys.provider_profile_incomplete'] = 'The provider did not return the required profile data.';
$lang['sys.provider_state_invalid'] = 'The external auth session is invalid or expired.';
$lang['sys.provider_auth_failed'] = 'External authentication failed. Please try again.';
$lang['sys.account_link_email_sent'] = 'We sent an email to confirm linking the external account.';
$lang['sys.account_link_completed'] = 'The external account has been linked successfully.';
$lang['sys.imports_property_definitions'] = 'JSON: property types / properties / sets';
$lang['sys.import_source_property_map'] = 'Direct property mapping';
$lang['sys.import_source_property_map_help'] = 'Use one mapping per line: source_property_id = local property name or source_property_id = #123. This is used for direct WP meta import into existing curated EE properties.';
$lang['sys.imports_stage_1_label'] = 'Run stage 1';
$lang['sys.imports_stage_1_running'] = 'Stage 1 is running...';
$lang['sys.imports_stage_1_done'] = 'Stage 1 completed';
$lang['sys.imports_stage_1_error'] = 'Stage 1 failed';
$lang['sys.imports_stage_2_label'] = 'Run stage 2';
$lang['sys.imports_stage_2_running'] = 'Stage 2 is running...';
$lang['sys.imports_stage_2_done'] = 'Stage 2 completed';
$lang['sys.imports_stage_2_error'] = 'Stage 2 failed';
$lang['sys.imports_full_label'] = 'Run all stages';
$lang['sys.imports_full_running'] = 'Full import is running...';
$lang['sys.imports_full_done'] = 'Full import completed';
$lang['sys.imports_full_error'] = 'Full import failed';
$lang['sys.tools'] = 'Tools';
$lang['sys.email_templates'] = 'Email templates';
$lang['sys.system'] = 'System';
$lang['sys.snippets'] = 'Snippets';
$lang['sys.vars'] = 'Vars';
$lang['sys.archive'] = 'Archive';
$lang['sys.theme'] = 'Theme';
$lang['sys.back'] = 'Back';
$lang['sys.add_email_template'] = 'Add email template';
$lang['sys.edit_email_template'] = 'Edit email template';
$lang['sys.enter_name'] = 'Enter name';
$lang['sys.subject'] = 'Subject';
$lang['sys.enter_subject'] = 'Enter subject';
$lang['sys.enter_description'] = 'Enter description';
$lang['sys.body'] = 'Body';
$lang['sys.enter_body'] = 'Enter body';
$lang['sys.preview'] = 'Preview';
$lang['sys.error'] = 'Error';
$lang['sys.removed'] = 'Removed';
$lang['sys.require_password_setup'] = 'Require password setup';
$lang['sys.ip_restricted'] = 'Restrict authorization by IP';
$lang['sys.local_password'] = 'Local password';
$lang['sys.failed_attempts'] = 'Failed attempts';
$lang['sys.locked_until'] = 'Locked until';
$lang['sys.linked_providers'] = 'Linked providers';
$lang['sys.no_linked_providers'] = 'No linked external providers yet.';
$lang['sys.restore_user'] = 'Restore user';
$lang['sys.restore_user_confirm'] = 'Restore this user and require a new password setup?';
$lang['sys.user_restored'] = 'User has been restored.';
$lang['sys.single_admin_only'] = 'Only one administrator can exist in the system.';
$lang['sys.single_admin_demotion_forbidden'] = 'You cannot remove the role from the only administrator.';
$lang['sys.language'] = 'Language';
$lang['sys.content_language'] = 'Content language';
$lang['sys.language_switch_help'] = 'Switching reloads the form and related lists in the selected locale.';
$lang['sys.translations'] = 'Translations';
$lang['sys.translation_source'] = 'Source version';
$lang['sys.translation_draft_help'] = 'A new translation is being created from the selected source version.';
$lang['sys.translation_list_help'] = 'The list shows records in the selected interface locale. Existing translations can be opened directly from the table.';
$lang['sys.category_edit'] = 'Edit category';
$lang['sys.category_add'] = 'Create category';
$lang['search.title'] = 'Control Panel Search';
$lang['search.breadcrumb_results'] = 'Search Results';
$lang['search.you_searched_for'] = 'You searched for';
$lang['search.results_found'] = 'Results found';
$lang['search.results_list_title'] = 'List of Found Materials';
$lang['search.result_relevance'] = 'Relevance';
$lang['search.no_results_found'] = 'Nothing was found for your query. Try changing the wording.';
$lang['search.enter_query'] = 'Please enter a search query in the form above.';
return $lang;
