<?php

/**
 * Евгений Ефимченко, efimchenko.com
 * Содержит языковые строки для английской локализации интерфейса EE_FrameWork.
 * /inc/langs/EN.php
 */
$lang = [
    'sys.imports_profiles_list' => 'Import Profiles',
    'sys.imports_management' => 'Import Management',
    'sys.imports_new_profile_wp' => 'Create WordPress Profile',
    'sys.imports_description' => 'Here you can manage your saved import profiles.',
    'sys.imports_no_profiles' => 'No import profiles found yet.',
    'sys.imports_last_run' => 'Last Run',
    'sys.imports_type_db' => 'Type',
    'sys.imports_db_connection' => 'DB Connection',
    'sys.imports_adapter_file' => 'Adapter File',
    'sys.imports_sql_dump' => 'SQL Dump File',
    'sys.imports_edit_profile' => 'Edit Import Profile',
    'sys.imports_new_profile' => 'New Import Profile',
    'sys.imports_settings' => 'Settings',
    'sys.imports_profile_name' => 'Profile Name',
    'sys.imports_what_to_import' => 'What to Import',
    'sys.imports_core_content' => 'Core Content (Posts, Pages, Categories, Media)',
    'sys.imports_woo_data' => 'WooCommerce Data (Products, Orders)',
    'sys.imports_how_to_import' => 'Import Method',
    'sys.imports_db_host' => 'DB Host',
    'sys.imports_db_name' => 'DB Name',
    'sys.imports_db_user' => 'DB User',
    'sys.imports_db_pass' => 'DB Password',
    'sys.imports_db_pref' => 'Table Prefix',
    'sys.imports_adapter_path' => 'Path to Adapter File',
    'sys.imports_adapter_help' => 'Specify the full server path to the PHP file that will return the data array for import.',
    'sys.imports_sql_dump_path' => 'Path to .sql File',
    'sys.imports_sql_dump_help' => 'Full server path to the .sql dump file. The script will create a temporary DB using the credentials below.',
    'sys.imports_temp_db_creds' => 'Credentials for Temp DB',
    'sys.imports_run' => 'Run Import',
    'sys.imports_cron_run' => 'Run via CRON',
    'sys.imports_cron_help' => 'To run this profile automatically, use the command:',
    'sys.imports_log' => 'Execution Log',
    'sys.imports_saving' => 'Saving...',
    'sys.imports_running' => 'Running...',
    'sys.imports_done' => 'Done.',
    'sys.imports_error' => 'Error.',
    'sys.imports_sql_dump' => 'SQL Dump File',
    'sys.imports_sql_dump_help' => 'Upload a .sql, .gz, .gzip, or .zip file. A temporary DB will be created using the credentials (Host/User/Pass) specified above.',
    'sys.imports_temp_db_creds' => 'Credentials for Temp DB',
    'sys.imports_adapter_download' => 'Download ee_wp_exporter.php',
    'sys.imports_exporter_title' => 'WordPress Exporter Script',
    'sys.imports_exporter_help_1' => '1. Download exporter script.',
    'sys.imports_exporter_help_2' => '2. Upload it to WordPress root.',
    'sys.imports_exporter_help_3' => '3. Run it in browser, then upload generated package here.',
    'sys.imports_upload_package' => 'Upload JSON/JSONL package (.zip, .jsonl, .json)',
    'sys.imports_no_file_uploaded' => 'No package uploaded yet.',
    'sys.imports_file_limit' => 'Max upload size',
    'sys.save_settings' => 'Save settings',
    'sys.imports_test_mode' => 'Test Mode',
    'sys.imports_test_mode_enable' => 'Enable Test Mode',
    'sys.imports_test_mode_limit' => 'Import records limit:',
    'sys.imports_test_connection' => 'Test Connection',
    'sys.imports_err_posts_not_found' => 'Connection successful, but _posts table not found.',
    'sys.imports_ok_connection' => 'Success! Found prefix:',
    'sys.imports_saving' => 'Saving...',
    'sys.imports_running' => 'Running...',
    'sys.imports_done' => 'Done.',
    'sys.imports_error' => 'Error.',
    'sys.imports_delete_confirm' => 'Are you sure you want to delete this import profile? All associated files (dumps) and logs will also be deleted.',
    'sys.imports_need_save' => 'Settings have changed. Please save the profile.',
    'sys.imports_sql_dump_help_v2' => 'Upload a .sql, .gz, .gzip, or .zip file. The import will use your website\'s current database connection settings.',
    'sys.imports_upload_new_dump' => 'Upload new dump file',
    'sys.imports_current_file' => 'Current file',
    'sys.imports_upload_adapter_file' => 'Upload .json/.zip file',
    'sys.imports_delete_confirm' => 'Are you sure you want to delete this import profile? All associated files (dumps) and logs will also be deleted.',
    'sys.imports_need_save' => 'File selected. Please save the profile to run the import.',
    'sys.imports_file_too_large' => 'The file might be too large.',   
];
$lang['sys.general'] = 'General';
$lang['sys.email'] = 'Email';
$lang['sys.your_email'] = 'Your email';
$lang['sys.test_email'] = 'Email for sending verification message';
$lang['sys.send_email'] = 'Send';
$lang['sys.password'] = 'Password';
$lang['sys.new_password'] = 'New Password';
$lang['sys.your_password'] = 'Your password';
$lang['sys.confirm_password'] = 'Confirm password';
$lang['sys.restore_password'] = 'Restore password';
$lang['sys.restore_password_process'] = 'Password recovery';
$lang['sys.log_in'] = 'Log In';
$lang['sys.log_out'] = 'Logout';
$lang['sys.sign_up'] = 'Sign Up';
$lang['sys.sign_up_text'] = 'Registration';
$lang['sys.welcome'] = 'Welcome';
$lang['sys.verify_email'] = 'We have sent a letter with a verification code to your email';
$lang['sys.new_password_in_email'] = 'We have sent you an email with a new password.';
$lang['sys.recovery_link_sent'] = 'We have sent a password recovery link to your email.';
$lang['sys.password_setup_link_sent'] = 'We have sent a password setup link to your email.';
$lang['sys.password_setup_mail_failed'] = 'Failed to send the password setup email.';
$lang['sys.password_setup'] = 'Password setup';
$lang['sys.password_setup_intro'] = 'Set a new password to continue using your account.';
$lang['sys.password_setup_completed'] = 'Password has been set successfully. You will be redirected now.';
$lang['sys.password_setup_reason'] = 'Password setup reason';
$lang['sys.password_too_short'] = 'Password must contain at least 5 characters.';
$lang['sys.password_changed_successfully'] = 'Password changed successfully. You will be redirected now.';
$lang['sys.set_new_password'] = 'Enter a new password to complete this action.';
$lang['sys.save_password'] = 'Save password';
$lang['sys.challenge_invalid'] = 'The link is invalid or has expired.';
$lang['sys.data_read_error'] = 'Data read error';
$lang['sys.data_being_saved'] = 'Please wait, the data is being saved';
$lang['sys.data_update_error'] = 'Data update error.';
$lang['sys.personal_data_updated'] = 'Personal settings have been updated';
$lang['sys.invalid_mail_format'] = 'Invalid email format.';
$lang['sys.no_connection_to_db'] = 'No connection to DB';
$lang['sys.db_registration_error'] = 'DB registration error';
$lang['sys.success'] = 'Success';
$lang['sys.the_mail_is_already_busy'] = 'The email is already taken';
$lang['sys.password_mismatch'] = 'Password mismatch';
$lang['sys.email_sending_error'] = 'Email sending error';
$lang['sys.successfully_activated'] = 'You have successfully activated your account and will be redirected.';
$lang['sys.activation_error'] = 'An activation error has occurred, the code has expired or does not exist. The data is cleared, please register again.';
$lang['sys.account_is_already_active'] = 'Your account is already activated.';
$lang['sys.you_were_blocked'] = 'We are sorry, but you were blocked, contact the site administrator.';
$lang['sys.account_deleted'] = 'This account has been deleted. Please contact the site administrator.';
$lang['sys.email_not_registered'] = 'Sorry, but you have not registered such email.';
$lang['sys.is_under_development'] = 'Sorry, but the functionality is under development.';
$lang['sys.no_such_data_was_found'] = 'No such user was found.';
$lang['sys.the_password_was_not_verified'] = 'The password is not correct.';
$lang['sys.you_have_not_verified_your_email'] = 'You have not verified your email.';
$lang['sys.account_is_blocked'] = 'Account is blocked.';
$lang['sys.unknown'] = 'Unknown';
$lang['sys.not_confirmed'] = 'Not verified';
$lang['sys.active'] = 'Аctive';
$lang['sys.hidden'] = 'Hidden';
$lang['sys.disabled'] = 'Disabled';
$lang['sys.blocked'] = 'Blocked';
$lang['sys.no_access'] = 'Access denied';
$lang['sys.no_data'] = 'No data';
$lang['sys.admin'] = 'Administrator';
$lang['sys.dashboard'] = 'Dashboard';
$lang['sys.name'] = 'Name';
$lang['sys.value'] = 'Value';
$lang['sys.description'] = 'Description';
$lang['sys.short_description'] = 'Short description';
$lang['sys.content'] = 'Contents';
$lang['sys.phone'] = 'Phone';
$lang['sys.site'] = 'Website';
$lang['sys.status'] = 'Status';
$lang['sys.not_assigned'] = 'Not assigned';
$lang['sys.default'] = 'Default';
$lang['sys.optional'] = 'Optional';
$lang['sys.title'] = 'Title';
$lang['sys.enter_title'] = 'Enter the title';
$lang['sys.sort'] = 'Sorting';
$lang['sys.heading'] = 'Heading';
$lang['sys.date'] = 'Date';
$lang['sys.time'] = 'Time';
$lang['sys.edit'] = 'Edit';
$lang['sys.used'] = 'Used';
$lang['sys.delete'] = 'Delete';
$lang['sys.save'] = 'Save';
$lang['sys.delete_all'] = 'Delete everything';
$lang['sys.clear'] = 'Сlear';
$lang['sys.clear_file'] = 'Сlear file';
$lang['sys.file_name'] = 'File name';
$lang['sys.allowed_files'] = 'Allowed files';
$lang['sys.file_marked_for_delete'] = 'File will be deleted after saving the form';
$lang['sys.undo_delete'] = 'Undo deletion';
$lang['sys.file_unavailable'] = 'File unavailable';
$lang['sys.external_reference'] = 'External reference';
$lang['sys.legacy_reference'] = 'Legacy reference';
$lang['sys.apply_filters'] = 'Apply filters';
$lang['sys.activity'] = 'Activity';
$lang['sys.role'] = 'Role';
$lang['sys.roles'] = 'Roles';
$lang['sys.action'] = 'Action';
$lang['sys.actions'] = 'Actions';
$lang['sys.add'] = 'Add';
$lang['sys.ip'] = 'IP';
$lang['sys.last_ip'] = 'Last IP';
$lang['sys.registered_users'] = 'Registered users';
$lang['sys.user_info'] = 'User info';
$lang['sys.users'] = 'Users';
$lang['sys.deleted_users'] = 'Deleted';
$lang['sys.categories'] = 'Categories';
$lang['sys.category'] = 'Category';
$lang['sys.pages'] = 'Pages';
$lang['sys.page'] = 'Page';
$lang['sys.filters_management'] = 'Filters management';
$lang['sys.entities'] = 'Entities';
$lang['sys.entity'] = 'Entity';
$lang['sys.message'] = 'Message';
$lang['sys.messages'] = 'Messages';
$lang['sys.all'] = 'All';
$lang['sys.read'] = 'Read';
$lang['sys.mark_as_read'] = 'Mark as read';
$lang['sys.mark_everything_as_read'] = 'Mark everything as read';
$lang['sys.category_pages'] = 'Category pages';
$lang['sys.sets'] = 'Sets';
$lang['sys.set'] = 'Set';
$lang['sys.features'] = 'Features';
$lang['sys.type_categories'] = 'Category types';
$lang['sys.parent'] = 'Parent';
$lang['sys.author'] = 'Автор';
$lang['sys.type'] = 'Type';
$lang['sys.types'] = 'Types';
$lang['sys.scope'] = 'Scope';
$lang['sys.target'] = 'Target';
$lang['sys.property'] = 'Property';
$lang['sys.properties'] = 'Properties';
$lang['sys.property_sets'] = 'Property sets';
$lang['sys.property_lifecycle_jobs'] = 'Property lifecycle jobs';
$lang['sys.property_lifecycle_run_next'] = 'Run next queued job';
$lang['sys.date_create'] = 'Date of creation';
$lang['sys.date_update'] = 'Update date';
$lang['sys.created'] = 'Created';
$lang['sys.updated'] = 'Updated';
$lang['sys.progress'] = 'Progress';
$lang['sys.date_activity'] = 'Activity date';
$lang['sys.read_at'] = 'Date read';
$lang['sys.user_edit'] = 'Editing a user';
$lang['sys.categories_edit'] = 'Editing categories';
$lang['sys.comment'] = 'A comment';
$lang['sys.safety'] = 'Safety';
$lang['sys.basics'] = 'Basics';
$lang['sys.list'] = 'List';
$lang['sys.list_properties_for_set'] = 'List of properties for the set';
$lang['sys.select'] = 'Select';
$lang['sys.yes'] = 'Yes';
$lang['sys.no'] = 'No';
$lang['sys.fields'] = 'Fields';
$lang['sys.field_type'] = 'Field_type';
$lang['sys.field'] = 'Field';
$lang['sys.empty'] = 'Empty';
$lang['sys.separate_window'] = 'Separate window';
$lang['sys.multiple_choice'] = 'Multiple choice';
$lang['sys.required'] = 'Required';
$lang['sys.logs'] = 'Logs';
$lang['sys.php_logs'] = 'PHP logs';
$lang['sys.fatal_logs'] = 'Fatal logs';
$lang['sys.project_logs'] = 'Project logs';
$lang['sys.clear_html_cache'] = 'Clear HTML cache';
$lang['sys.clear_route_cache'] = 'Clear route cache';
$lang['sys.reset_redis_probe'] = 'Reset Redis probe';
$lang['sys.clear_php_logs'] = 'Clear PHP logs';
$lang['sys.clear_fatal_logs'] = 'Clear fatal logs';
$lang['sys.clear_project_logs'] = 'Clear project logs';
$lang['sys.cache_html_cleared'] = 'HTML cache has been cleared.';
$lang['sys.cache_route_cleared'] = 'Route cache has been cleared.';
$lang['sys.redis_probe_reset'] = 'Redis availability probe will be executed again.';
$lang['sys.health'] = 'System health';
$lang['sys.install'] = 'Installation';
$lang['sys.core_tables'] = 'Core tables';
$lang['sys.auth_infrastructure'] = 'Auth infrastructure';
$lang['sys.paths'] = 'Paths';
$lang['sys.path'] = 'Path';
$lang['sys.exists'] = 'Exists';
$lang['sys.writable'] = 'Writable';
$lang['sys.cache'] = 'Cache';
$lang['sys.route_cache'] = 'Route cache';
$lang['sys.queued'] = 'Queued';
$lang['sys.running'] = 'Running';
$lang['sys.failed'] = 'Failed';
$lang['sys.stale_jobs'] = 'Stale jobs';
$lang['sys.recover_stale_jobs'] = 'Recover stale jobs';
$lang['sys.media_diagnostics'] = 'Media diagnostics';
$lang['sys.refresh_media_metadata'] = 'Refresh media metadata';
$lang['sys.referenced_files'] = 'Referenced files';
$lang['sys.unreferenced_files'] = 'Unreferenced files';
$lang['sys.missing_on_disk'] = 'Missing on disk';
$lang['sys.dangling_references'] = 'Dangling references';
$lang['sys.legacy_payloads'] = 'Legacy payloads';
$lang['sys.run_backup'] = 'Create backup';
$lang['sys.snapshots'] = 'Snapshots';
$lang['sys.total'] = 'Total';
$lang['sys.backup'] = 'Backup';
$lang['sys.fill_with_test_data'] = 'Fill with test data';
$lang['sys.delete_database_data'] = 'Delete database data';
$lang['sys.project_development'] = 'Project development';
$lang['sys.order_a_project'] = 'Order a project';
$lang['sys.review'] = 'Review';
$lang['sys.kill_db'] = 'All database tables will be deleted!';
$lang['sys.error_type'] = 'Error type';
$lang['sys.stack_trace'] = 'Stack trace';
$lang['sys.log_channel'] = 'Channel';
$lang['sys.log_channels'] = 'Channels';
$lang['sys.file_count'] = 'Files';
$lang['sys.archive_count'] = 'Archives';
$lang['sys.log_size'] = 'Size';
$lang['sys.last_update'] = 'Last update';
$lang['sys.level'] = 'Level';
$lang['sys.request_id'] = 'Request ID';
$lang['sys.request'] = 'Request';
$lang['sys.context'] = 'Context';
$lang['sys.meta'] = 'Meta';
$lang['sys.initiator'] = 'Initiator';
$lang['sys.result'] = 'Result';
$lang['sys.details'] = 'Details';
$lang['sys.subscribed'] = 'Subscribed';
$lang['sys.filtres'] = 'Filtres';
$lang['sys.database'] = 'DataBase';
$lang['sys.copy'] = 'Copy';
$lang['sys.insert'] = 'Insert';
$lang['sys.cancel'] = 'Cancel';
$lang['sys.close'] = 'Сlose';
$lang['sys.download'] = 'Download';
$lang['sys.authorization'] = 'Authorization';
$lang['sys.continue_with_google'] = 'Continue with Google';
$lang['sys.provider_not_configured'] = 'The selected auth provider is not configured yet.';
$lang['sys.provider_profile_incomplete'] = 'The provider did not return the required profile data.';
$lang['sys.provider_state_invalid'] = 'The external auth session is invalid or expired.';
$lang['sys.provider_auth_failed'] = 'External authentication failed. Please try again.';
$lang['sys.account_link_email_sent'] = 'We sent an email to confirm linking the external account.';
$lang['sys.account_link_completed'] = 'The external account has been linked successfully.';
$lang['sys.imports_property_definitions'] = 'JSON: property types / properties / sets';
$lang['sys.tools'] = 'Tools';
$lang['sys.email_templates'] = 'Email templates';
$lang['sys.content'] = 'Content';
$lang['sys.system'] = 'System';
$lang['sys.snippets'] = 'Snippets';
$lang['sys.vars'] = 'Vars';
$lang['sys.archive'] = 'Archive';
$lang['sys.theme'] = 'Theme';
$lang['sys.back'] = 'Back';
$lang['sys.add_email_template'] = 'Add email template';
$lang['sys.edit_email_template'] = 'Edit email template';
$lang['sys.enter_name'] = 'Enter name';
$lang['sys.subject'] = 'Subject';
$lang['sys.enter_subject'] = 'Enter subject';
$lang['sys.enter_description'] = 'Enter description';
$lang['sys.body'] = 'Body';
$lang['sys.enter_body'] = 'Enter body';
$lang['sys.preview'] = 'Preview';
$lang['sys.error'] = 'Error';
$lang['sys.removed'] = 'Removed';
$lang['sys.require_password_setup'] = 'Require password setup';
$lang['sys.ip_restricted'] = 'Restrict authorization by IP';
$lang['sys.local_password'] = 'Local password';
$lang['sys.failed_attempts'] = 'Failed attempts';
$lang['sys.locked_until'] = 'Locked until';
$lang['sys.linked_providers'] = 'Linked providers';
$lang['sys.no_linked_providers'] = 'No linked external providers yet.';
$lang['sys.restore_user'] = 'Restore user';
$lang['sys.restore_user_confirm'] = 'Restore this user and require a new password setup?';
$lang['sys.user_restored'] = 'User has been restored.';
$lang['search.title'] = 'Control Panel Search';
$lang['search.breadcrumb_results'] = 'Search Results';
$lang['search.you_searched_for'] = 'You searched for';
$lang['search.results_found'] = 'Results found';
$lang['search.results_list_title'] = 'List of Found Materials';
$lang['search.result_relevance'] = 'Relevance';
$lang['search.no_results_found'] = 'Nothing was found for your query. Try changing the wording.';
$lang['search.enter_query'] = 'Please enter a search query in the form above.';
return $lang;
