<?php

/**
 * System words
 */
$lang = [
    'sys.imports_profiles_list' => 'Профили импорта',
    'sys.imports_management' => 'Управление импортами',
    'sys.imports_new_profile_wp' => 'Создать профиль WordPress',
    'sys.imports_description' => 'Здесь вы можете управлять сохраненными профилями импорта.',
    'sys.imports_no_profiles' => 'Сохраненных профилей импорта пока нет.',
    'sys.imports_last_run' => 'Последний запуск',
    'sys.imports_type_db' => 'Тип',
    'sys.imports_db_connection' => 'Подключение к БД',
    'sys.imports_adapter_file' => 'Файл-адаптер',
    'sys.imports_edit_profile' => 'Редактирование профиля импорта',
    'sys.imports_new_profile' => 'Новый профиль импорта',
    'sys.imports_settings' => 'Настройки',
    'sys.imports_profile_name' => 'Название профиля',
    'sys.imports_what_to_import' => 'Что импортировать',
    'sys.imports_core_content' => 'Основной контент (Посты, Страницы, Рубрики, Медиа)',
    'sys.imports_woo_data' => 'Данные WooCommerce (Товары, Заказы)',
    'sys.imports_how_to_import' => 'Способ импорта',
    'sys.imports_db_host' => 'Хост БД',
    'sys.imports_db_name' => 'Имя БД',
    'sys.imports_db_user' => 'Пользователь БД',
    'sys.imports_db_pass' => 'Пароль БД',
    'sys.imports_db_pref' => 'Префикс таблиц',
    'sys.imports_adapter_path' => 'Путь к файлу-адаптеру',
    'sys.imports_adapter_help' => 'Укажите полный путь на сервере к PHP-файлу, который вернет массив данных для импорта.',
    'sys.imports_sql_dump_path' => 'Путь к .sql файлу',
    'sys.imports_run' => 'Запустить импорт',
    'sys.imports_cron_run' => 'Запуск через CRON',
    'sys.imports_cron_help' => 'Для автоматического запуска этого профиля используйте команду:',
    'sys.imports_log' => 'Лог выполнения',
    'sys.imports_sql_dump' => 'SQL Дамп',
    'sys.imports_sql_dump_help' => 'Загрузите .sql, .gz, .gzip или .zip файл. При импорте будет создана временная БД, используя учетные данные (Хост/Пользователь/Пароль) указанные выше.',
    'sys.imports_temp_db_creds' => 'Учетные данные для создания временной БД',
    'sys.imports_adapter_download' => 'Скачать ee_wp_exporter.php',
    'sys.imports_exporter_title' => 'Скрипт экспорта WordPress',
    'sys.imports_exporter_help_1' => '1. Скачайте скрипт экспортера.',
    'sys.imports_exporter_help_2' => '2. Загрузите его в корень WordPress.',
    'sys.imports_exporter_help_3' => '3. Запустите в браузере и загрузите сюда сформированный пакет.',
    'sys.imports_upload_package' => 'Загрузить пакет JSON/JSONL (.zip, .jsonl, .json)',
    'sys.imports_no_file_uploaded' => 'Пакет пока не загружен.',
    'sys.imports_file_limit' => 'Максимальный размер файла',
    'sys.save_settings' => 'Сохранить настройки',
    'sys.imports_test_mode' => 'Тестовый режим',
    'sys.imports_test_mode_enable' => 'Включить тестовый режим',
    'sys.imports_test_mode_limit' => 'Импортировать записей:',
    'sys.imports_test_connection' => 'Проверить соединение',
    'sys.imports_err_posts_not_found' => 'Подключение есть, но таблица _posts не найдена.',
    'sys.imports_ok_connection' => 'Успешно! Найден префикс:',
    'sys.imports_saving' => 'Сохранение...',
    'sys.imports_running' => 'Выполняется...',
    'sys.imports_done' => 'Завершено.',
    'sys.imports_error' => 'Ошибка.',
    'sys.imports_delete_confirm' => 'Вы уверены, что хотите удалить этот профиль импорта? Все связанные файлы (дампы) и логи также будут удалены.',
    'sys.imports_sql_dump_help_v2' => 'Загрузите .sql, .gz, .gzip или .zip файл. Импорт будет выполнен с использованием текущих настроек подключения к БД вашего сайта.',
    'sys.imports_upload_new_dump' => 'Загрузить новый файл дампа',
    'sys.imports_current_file' => 'Текущий файл',
    'sys.imports_upload_adapter_file' => 'Загрузить .json/.zip файл',
    'sys.imports_need_save' => 'Файл выбран. Сохраните профиль, чтобы запустить импорт.',
    'sys.imports_file_too_large' => 'Возможно, файл слишком большой.',   
    ];
$lang['sys.email'] = 'Почта';
$lang['sys.general'] = 'Главная';
$lang['sys.your_email'] = 'Ваша почта';
$lang['sys.test_email'] = 'Почта для отправки проверочного сообщения';
$lang['sys.send_email'] = 'Отправить';
$lang['sys.password'] = 'Пароль';
$lang['sys.new_password'] = 'Новый пароль';
$lang['sys.your_password'] = 'Ваш пароль';
$lang['sys.confirm_password'] = 'Повторите пароль';
$lang['sys.restore_password'] = 'Восстановить пароль';
$lang['sys.restore_password_process'] = 'Восстановление пароля';
$lang['sys.log_in'] = 'Войти';
$lang['sys.log_out'] = 'Выйти';
$lang['sys.sign_up'] = 'Зарегистрироваться';
$lang['sys.sign_up_text'] = 'Регистрация';
$lang['sys.welcome'] = 'Добро пожаловать';
$lang['sys.verify_email'] = 'Мы выслали к вам на почту письмо с проверочным кодом.';
$lang['sys.new_password_in_email'] = 'Мы выслали к вам на почту письмо с новым паролем доступа.';
$lang['sys.recovery_link_sent'] = 'Мы выслали ссылку для восстановления пароля на вашу почту.';
$lang['sys.password_setup_link_sent'] = 'Мы выслали ссылку для назначения пароля на вашу почту.';
$lang['sys.password_setup_mail_failed'] = 'Не удалось отправить письмо для назначения пароля.';
$lang['sys.password_setup'] = 'Назначение пароля';
$lang['sys.password_setup_intro'] = 'Задайте новый пароль для продолжения работы с аккаунтом.';
$lang['sys.password_setup_completed'] = 'Пароль успешно назначен. Сейчас вы будете перенаправлены.';
$lang['sys.password_setup_reason'] = 'Причина назначения пароля';
$lang['sys.password_too_short'] = 'Пароль должен содержать не менее 5 символов.';
$lang['sys.password_changed_successfully'] = 'Пароль успешно изменён. Сейчас вы будете перенаправлены.';
$lang['sys.set_new_password'] = 'Введите новый пароль для завершения операции.';
$lang['sys.save_password'] = 'Сохранить пароль';
$lang['sys.challenge_invalid'] = 'Ссылка недействительна или срок её действия истёк.';
$lang['sys.data_read_error'] = 'Ошибка чтения данных.';
$lang['sys.data_being_saved'] = 'Подождите данные сохраняются.';
$lang['sys.data_update_error'] = 'Ошибка обновления данных.';
$lang['sys.personal_data_updated'] = 'Личные настройки обновлены.';
$lang['sys.invalid_mail_format'] = 'Неверный формат почты.';
$lang['sys.no_connection_to_db'] = 'Нет соединения с БД';
$lang['sys.db_registration_error'] = 'Ошибка регистрации в БД';
$lang['sys.success'] = 'Успешно';
$lang['sys.the_mail_is_already_busy'] = 'Почта уже занята.';
$lang['sys.password_mismatch'] = 'Пароли не совпадают.';
$lang['sys.email_sending_error'] = 'Ошибка отправления письма.';
$lang['sys.successfully_activated'] = 'Вы успешно активировали свой аккаунт. И будете перенаправлены.';
$lang['sys.activation_error'] = 'Произошла ошибка активации, код был просрочен или не существует. Данные очищены, пройдите регистрацию вновь.';
$lang['sys.account_is_already_active'] = 'Ваш аккаунт уже активен.';
$lang['sys.you_were_blocked'] = 'Сожалеем, но Вас заблокировали, обратитесь к администратору сайта.';
$lang['sys.account_deleted'] = 'Аккаунт удалён. Обратитесь к администратору сайта.';
$lang['sys.email_not_registered'] = 'Извините, но Вы у нас не регистрировались с такой почтой.';
$lang['sys.is_under_development'] = 'Извините, но функционал на стадии разработки.';
$lang['sys.no_such_data_was_found'] = 'Такие данные не обнаружены.';
$lang['sys.the_password_was_not_verified'] = 'Пароль не прошёл проверку.';
$lang['sys.you_have_not_verified_your_email'] = 'Вы не подтвердили электронную почту.';
$lang['sys.account_is_blocked'] = 'Аккаунт заблокирован';
$lang['sys.unknown'] = 'Неизвестен';
$lang['sys.not_confirmed'] = 'Не подтверждён';
$lang['sys.active'] = 'Активен';
$lang['sys.hidden'] = 'Скрыт';
$lang['sys.disabled'] = 'Отключен';
$lang['sys.blocked'] = 'Заблокирован';
$lang['sys.no_access'] = 'Нет доступа';
$lang['sys.no_data'] = 'Нет данных';
$lang['sys.admin'] = 'Администратор';
$lang['sys.dashboard'] = 'Панель приборов';
$lang['sys.name'] = 'Имя';
$lang['sys.value'] = 'Значение';
$lang['sys.description'] = 'Описание';
$lang['sys.short_description'] = 'Краткое описание';
$lang['sys.content'] = 'Контент';
$lang['sys.phone'] = 'Телефон';
$lang['sys.site'] = 'Сайт';
$lang['sys.status'] = 'Статус';
$lang['sys.not_assigned'] = 'Не назначено';
$lang['sys.default'] = 'По умолчанию';
$lang['sys.optional'] = 'Опционально';
$lang['sys.title'] = 'Название';
$lang['sys.enter_title'] = 'Введите название';
$lang['sys.sort'] = 'Сортировка';
$lang['sys.heading'] = 'Заголовок';
$lang['sys.date'] = 'Дата';
$lang['sys.time'] = 'Время';
$lang['sys.edit'] = 'Редактировать';
$lang['sys.delete'] = 'Удалить';
$lang['sys.save'] = 'Сохранить';
$lang['sys.used'] = 'Используется';
$lang['sys.delete_all'] = 'Удалить Всё';
$lang['sys.clear'] = 'Очистить';
$lang['sys.clear_file'] = 'Очистить файл';
$lang['sys.file_name'] = 'Название файла';
$lang['sys.allowed_files'] = 'Допустимые файлы';
$lang['sys.file_marked_for_delete'] = 'Файл будет удалён после сохранения формы';
$lang['sys.undo_delete'] = 'Отменить удаление';
$lang['sys.file_unavailable'] = 'Файл недоступен';
$lang['sys.external_reference'] = 'Внешняя ссылка';
$lang['sys.legacy_reference'] = 'Устаревшая ссылка';
$lang['sys.apply_filters'] = 'Применить фильтры';
$lang['sys.activity'] = 'Активность';
$lang['sys.role'] = 'Роль';
$lang['sys.roles'] = 'Роли';
$lang['sys.action'] = 'Действие';
$lang['sys.actions'] = 'Действия';
$lang['sys.add'] = 'Добавить';
$lang['sys.ip'] = 'IP адрес';
$lang['sys.last_ip'] = 'Последний IP';
$lang['sys.registered_users'] = 'Зарегистрированные пользователи';
$lang['sys.user_info'] = 'Данные пользователя';
$lang['sys.users'] = 'Пользователи';
$lang['sys.deleted_users'] = 'Удалённые';
$lang['sys.categories'] = 'Категории';
$lang['sys.category'] = 'Категория';
$lang['sys.pages'] = 'Страницы';
$lang['sys.page'] = 'Страница';
$lang['sys.entities'] = 'Сущности';
$lang['sys.entity'] = 'Сущность';
$lang['sys.filters_management'] = 'Управление фильтрами';
$lang['sys.message'] = 'Сообщение';
$lang['sys.messages'] = 'Сообщения';
$lang['sys.all'] = 'Все';
$lang['sys.read'] = 'Прочитано';
$lang['sys.mark_as_read'] = 'Пометить, как прочитанное';
$lang['sys.mark_everything_as_read'] = 'Отметить все как прочитанное';
$lang['sys.category_pages'] = 'Страницы категории';
$lang['sys.sets'] = 'Наборы';
$lang['sys.set'] = 'Набор';
$lang['sys.type_categories'] = 'Типы категорий';
$lang['sys.parent'] = 'Родитель';
$lang['sys.author'] = 'Автор';
$lang['sys.type'] = 'Тип';
$lang['sys.types'] = 'Типы';
$lang['sys.scope'] = 'Область';
$lang['sys.target'] = 'Цель';
$lang['sys.property'] = 'Свойство';
$lang['sys.properties'] = 'Свойства';
$lang['sys.property_sets'] = 'Наборы свойств';
$lang['sys.property_lifecycle_jobs'] = 'Задачи жизненного цикла';
$lang['sys.property_lifecycle_run_next'] = 'Запустить следующую задачу';
$lang['sys.features'] = 'Характеристики';
$lang['sys.date_create'] = 'Дата создания';
$lang['sys.date_update'] = 'Дата обновления';
$lang['sys.created'] = 'Создано';
$lang['sys.updated'] = 'Обновлено';
$lang['sys.progress'] = 'Прогресс';
$lang['sys.date_activity'] = 'Дата активности';
$lang['sys.read_at'] = 'Дата прочтения';
$lang['sys.user_edit'] = 'Редактирование пользователя';
$lang['sys.categories_edit'] = 'Редактирование категорий';
$lang['sys.comment'] = 'Комментарий';
$lang['sys.safety'] = 'Безопасность';
$lang['sys.basics'] = 'Основное';
$lang['sys.list'] = 'Список';
$lang['sys.list_properties_for_set'] = 'Список свойств для набора';
$lang['sys.select'] = 'Выберите';
$lang['sys.yes'] = 'Да';
$lang['sys.no'] = 'Нет';
$lang['sys.fields'] = 'Поля';
$lang['sys.field_type'] = 'Тип поля';
$lang['sys.field'] = 'Поле';
$lang['sys.empty'] = 'Пусто';
$lang['sys.separate_window'] = 'Отдельное окно';
$lang['sys.multiple_choice'] = 'Множественное';
$lang['sys.required'] = 'Обязательное';
$lang['sys.logs'] = 'Логи';
$lang['sys.php_logs'] = 'PHP-логи';
$lang['sys.fatal_logs'] = 'Фатальные логи';
$lang['sys.project_logs'] = 'Логи проекта';
$lang['sys.clear_html_cache'] = 'Очистить HTML-кэш';
$lang['sys.clear_route_cache'] = 'Очистить route-кэш';
$lang['sys.reset_redis_probe'] = 'Сбросить проверку Redis';
$lang['sys.clear_php_logs'] = 'Очистить PHP-логи';
$lang['sys.clear_fatal_logs'] = 'Очистить фатальные логи';
$lang['sys.clear_project_logs'] = 'Очистить логи проекта';
$lang['sys.cache_html_cleared'] = 'HTML-кэш очищен.';
$lang['sys.cache_route_cleared'] = 'Route-кэш очищен.';
$lang['sys.redis_probe_reset'] = 'Проверка Redis будет выполнена заново.';
$lang['sys.cron_agents'] = 'Cron-агенты';
$lang['sys.cron_agent'] = 'Cron-агент';
$lang['sys.cron_agent_runs'] = 'История запусков cron-агентов';
$lang['sys.cron_agent_new'] = 'Новый cron-агент';
$lang['sys.cron_agent_edit'] = 'Редактирование cron-агента';
$lang['sys.cron_agent_saved'] = 'Cron-агент сохранён.';
$lang['sys.cron_agent_deleted'] = 'Cron-агент удалён.';
$lang['sys.cron_agent_not_found'] = 'Cron-агент не найден.';
$lang['sys.cron_agent_code'] = 'Код';
$lang['sys.cron_agent_handler'] = 'Handler';
$lang['sys.cron_agent_schedule_mode'] = 'Режим расписания';
$lang['sys.cron_agent_schedule_interval'] = 'Интервал';
$lang['sys.cron_agent_schedule_cron'] = 'Cron-выражение';
$lang['sys.cron_agent_schedule_manual'] = 'Только вручную';
$lang['sys.cron_agent_interval_minutes'] = 'Интервал, минут';
$lang['sys.cron_agent_cron_expression'] = 'Cron-выражение';
$lang['sys.cron_agent_payload_json'] = 'Payload JSON';
$lang['sys.cron_agent_payload_help'] = 'В payload храните только параметры запуска handler-а. Код обработчика остаётся в проекте.';
$lang['sys.cron_agent_handler_settings'] = 'Параметры handler-а';
$lang['sys.cron_agent_handler_settings_empty'] = 'Для этого handler-а нет отдельных параметров.';
$lang['sys.cron_agent_payload_batch_limit'] = 'Файлов за один тик';
$lang['sys.cron_agent_payload_batch_limit_help'] = 'Сколько элементов очереди медиа агент обработает за один запуск scheduler-а. Увеличивайте осторожно, чтобы не перегружать сервер.';
$lang['sys.cron_agent_payload_media_retry_delay'] = 'Повтор медиа после ошибки, сек';
$lang['sys.cron_agent_payload_media_retry_delay_help'] = 'Через сколько секунд media-worker повторит неудачную загрузку конкретного файла из очереди.';
$lang['sys.cron_agent_payload_media_time_budget'] = 'Временной бюджет, сек';
$lang['sys.cron_agent_payload_media_time_budget_help'] = 'Сколько секунд media-worker может обрабатывать очередь за один запуск до мягкой остановки по guard-лимиту.';
$lang['sys.cron_agent_payload_job_id'] = 'ID профиля импорта';
$lang['sys.cron_agent_payload_job_id_help'] = 'Идентификатор import profile, который должен запускать handler import.profile.';
$lang['sys.cron_agent_payload_min_hits'] = 'Минимум хитов';
$lang['sys.cron_agent_payload_min_hits_help'] = 'Минимальное количество хитов поискового запроса, после которого он участвует в пересчёте популярности.';
$lang['sys.cron_agent_payload_query_limit'] = 'Лимит запросов';
$lang['sys.cron_agent_payload_query_limit_help'] = 'Сколько популярных запросов обработать за один запуск.';
$lang['sys.cron_agent_payload_result_limit'] = 'Лимит результатов';
$lang['sys.cron_agent_payload_result_limit_help'] = 'Сколько верхних результатов усиливать для каждого поискового запроса.';
$lang['sys.cron_agent_payload_decay_factor'] = 'Коэффициент затухания';
$lang['sys.cron_agent_payload_decay_factor_help'] = 'Число от 0 до 1. Чем меньше значение, тем быстрее снижается накопленная популярность.';
$lang['sys.cron_agent_next_run'] = 'Следующий запуск';
$lang['sys.cron_agent_last_run'] = 'Последний запуск';
$lang['sys.cron_agent_run_now'] = 'Запустить сейчас';
$lang['sys.cron_agent_run_scheduler'] = 'Запустить scheduler';
$lang['sys.cron_agent_recover_stale'] = 'Восстановить зависшие cron-агенты';
$lang['sys.cron_agent_scheduler_help'] = 'Настройте системный cron на запуск этого скрипта каждую минуту:';
$lang['sys.cron_agent_scheduler_single_command'] = 'На сервере нужно настроить только одну команду минутного запуска:';
$lang['sys.cron_agent_bootstrap_notice'] = 'Обязательные системные агенты создаются автоматически при развёртывании платформы.';
$lang['sys.cron_agent_auto_created_list'] = 'Автоматически создаваемые системные агенты:';
$lang['sys.cron_agent_auto_created_hint'] = 'Обязательные системные агенты создаются автоматически при развёртывании и первом bootstrap приложения.';
$lang['sys.cron_agent_status_due'] = 'Готов к запуску';
$lang['sys.cron_agent_status_idle'] = 'Ожидает';
$lang['sys.cron_agent_status_cooldown'] = 'Пауза после ошибки';
$lang['sys.cron_agent_enable'] = 'Включить';
$lang['sys.cron_agent_disable'] = 'Отключить';
$lang['sys.cron_agent_weight'] = 'Вес нагрузки';
$lang['sys.cron_agent_max_runtime'] = 'Макс. время, сек';
$lang['sys.cron_agent_lock_ttl'] = 'TTL блокировки, сек';
$lang['sys.cron_agent_retry_delay'] = 'Задержка перед повтором, сек';
$lang['sys.cron_agent_recent_runs'] = 'Последние запуски';
$lang['sys.cron_agent_trigger_source'] = 'Источник запуска';
$lang['sys.cron_agent_worker_id'] = 'Worker';
$lang['sys.cron_agent_duration_ms'] = 'Длительность, мс';
$lang['sys.cron_agent_max_per_tick'] = 'Лимит задач за тик';
$lang['sys.cron_agent_max_weight'] = 'Лимит нагрузки';
$lang['sys.cron_agent_max_concurrent'] = 'Лимит одновременных задач';
$lang['sys.cron_agent_runs_retention_notice'] = 'История запусков очищается автоматически и не растёт бесконечно.';
$lang['sys.cron_agent_runs_retention_current'] = 'Сейчас в БД:';
$lang['sys.cron_agent_runs_retention_policy'] = 'Политика хранения:';
$lang['sys.cron_agent_runs_retention_days'] = 'дн.';
$lang['sys.cron_agent_runs_retention_rows'] = 'строк';
$lang['sys.cron_infrastructure'] = 'Cron-инфраструктура';
$lang['sys.cron_handler_property_lifecycle'] = 'Обработка очереди lifecycle';
$lang['sys.cron_handler_property_lifecycle_desc'] = 'Запускает следующую queued-задачу жизненного цикла свойств.';
$lang['sys.cron_handler_search_popularity'] = 'Пересчёт популярности поиска';
$lang['sys.cron_handler_search_popularity_desc'] = 'Пересчитывает популярность поисковых запросов и применяет затухание рейтинга.';
$lang['sys.cron_handler_import_profile'] = 'Импорт профиля';
$lang['sys.cron_handler_import_profile_desc'] = 'Запускает профиль импорта по payload.job_id.';
$lang['sys.cron_handler_media_mirror'] = 'Фоновая догрузка импортированных медиа';
$lang['sys.cron_handler_media_mirror_desc'] = 'Дозагружает внешние изображения и файлы из очереди импорта в локальное хранилище.';
$lang['sys.cron_handler_health_check'] = 'Проверка состояния системы';
$lang['sys.cron_handler_health_check_desc'] = 'Собирает сводный health-report системы.';
$lang['sys.imports_cron_agent_title'] = 'Для профиля импорта лучше использовать cron-агент';
$lang['sys.imports_cron_agent_desc'] = 'Создайте агент с handler import.profile и payload JSON с job_id. Тогда минутный scheduler сам запустит профиль по расписанию.';
$lang['sys.imports_cron_agent_create'] = 'Создать cron-агент для этого профиля';
$lang['sys.imports_cron_agent_manual'] = 'Разовый ручной запуск конкретного профиля по-прежнему доступен командой:';
$lang['sys.imports_cron_agent_sync'] = 'Синхронизировать cron-агент';
$lang['sys.imports_cron_agent_synced'] = 'Cron-агент профиля импорта синхронизирован.';
$lang['sys.imports_cron_agent_deleted'] = 'Cron-агент профиля импорта удалён.';
$lang['sys.imports_cron_agent_missing'] = 'Связанный cron-агент пока не создан.';
$lang['sys.health'] = 'Состояние системы';
$lang['sys.install'] = 'Установка';
$lang['sys.core_tables'] = 'Ключевые таблицы';
$lang['sys.auth_infrastructure'] = 'Auth-инфраструктура';
$lang['sys.paths'] = 'Пути';
$lang['sys.path'] = 'Путь';
$lang['sys.exists'] = 'Существует';
$lang['sys.writable'] = 'Доступно для записи';
$lang['sys.cache'] = 'Кэш';
$lang['sys.route_cache'] = 'Route-кэш';
$lang['sys.queued'] = 'В очереди';
$lang['sys.running'] = 'В работе';
$lang['sys.failed'] = 'С ошибкой';
$lang['sys.stale_jobs'] = 'Зависшие';
$lang['sys.recover_stale_jobs'] = 'Восстановить зависшие задачи';
$lang['sys.recover_stale_operations'] = 'Восстановить зависшие процессы';
$lang['sys.recover_stale_operations_done'] = 'Проверка зависших процессов завершена.';
$lang['sys.recover_stale_operations_failed'] = 'Не удалось восстановить зависшие процессы.';
$lang['sys.media_diagnostics'] = 'Диагностика медиа';
$lang['sys.media_queue'] = 'Очередь медиа';
$lang['sys.media_queue_pending'] = 'Ожидают';
$lang['sys.media_queue_running'] = 'В работе';
$lang['sys.media_queue_failed'] = 'С ошибкой';
$lang['sys.media_queue_terminal_failed'] = 'Без повтора';
$lang['sys.health_alerts'] = 'Оповещения системы';
$lang['sys.health_alerts_summary'] = 'Критично:';
$lang['sys.health_alerts_warning'] = 'Предупреждения:';
$lang['sys.health_alerts_info'] = 'Инфо:';
$lang['sys.health_no_alerts'] = 'Критичных и предупреждающих событий не найдено.';
$lang['sys.storage'] = 'Диск';
$lang['sys.disk_free'] = 'Свободно';
$lang['sys.disk_total'] = 'Всего';
$lang['sys.disk_used_percent'] = 'Использовано';
$lang['sys.health_alert_db_down_title'] = 'База данных недоступна';
$lang['sys.health_alert_db_down_message'] = 'Приложение не может подключиться к базе данных. Проверьте MariaDB/MySQL и лимиты памяти сервера.';
$lang['sys.health_alert_core_tables_title'] = 'Не все ключевые таблицы доступны';
$lang['sys.health_alert_core_tables_message'] = 'Часть основных таблиц фреймворка отсутствует или не читается.';
$lang['sys.health_alert_auth_tables_title'] = 'Повреждена auth-инфраструктура';
$lang['sys.health_alert_auth_tables_message'] = 'Таблицы аутентификации доступны не полностью. Логин и сессии могут работать нестабильно.';
$lang['sys.health_alert_cron_tables_title'] = 'Cron-инфраструктура доступна не полностью';
$lang['sys.health_alert_cron_tables_message'] = 'Часть таблиц планировщика отсутствует. Системные агенты не смогут работать штатно.';
$lang['sys.health_alert_path_missing_title'] = 'Не найден обязательный путь';
$lang['sys.health_alert_path_missing_message'] = 'Путь {path_key} отсутствует: {path_value}';
$lang['sys.health_alert_path_unwritable_title'] = 'Нет прав на запись в обязательный путь';
$lang['sys.health_alert_path_unwritable_message'] = 'Путь {path_key} недоступен для записи: {path_value}';
$lang['sys.health_alert_disk_critical_title'] = 'Критически мало места на диске';
$lang['sys.health_alert_disk_critical_message'] = 'Свободно только {free} из {total} ({used_percent}% занято). Нужна срочная очистка или расширение диска.';
$lang['sys.health_alert_disk_warning_title'] = 'Остаток места на диске снижается';
$lang['sys.health_alert_disk_warning_message'] = 'Свободно {free} из {total} ({used_percent}% занято). Следите за ростом медиа, backup и логов.';
$lang['sys.health_alert_cron_stalled_title'] = 'Минутный scheduler остановился';
$lang['sys.health_alert_cron_stalled_message'] = 'Последний запуск cron был {minutes} минут назад или не фиксировался вовсе.';
$lang['sys.health_alert_cron_delayed_title'] = 'Минутный scheduler запаздывает';
$lang['sys.health_alert_cron_delayed_message'] = 'Последний запуск cron был {minutes} минут назад.';
$lang['sys.health_alert_cron_failed_title'] = 'Есть cron-агенты с актуальными ошибками';
$lang['sys.health_alert_cron_failed_message'] = 'Количество cron-агентов с последней ошибкой: {count}.';
$lang['sys.health_alert_cron_stale_title'] = 'Обнаружены зависшие cron-агенты';
$lang['sys.health_alert_cron_stale_message'] = 'Количество stale-lock агентов: {count}.';
$lang['sys.health_alert_lifecycle_stale_title'] = 'Обнаружены зависшие lifecycle-задачи';
$lang['sys.health_alert_lifecycle_stale_message'] = 'Количество зависших lifecycle-задач: {count}.';
$lang['sys.health_alert_media_stale_title'] = 'Обнаружены зависшие элементы очереди медиа';
$lang['sys.health_alert_media_stale_message'] = 'Количество зависших media queue items: {count}.';
$lang['sys.health_alert_media_failed_title'] = 'В очереди медиа есть элементы с повторяемой ошибкой';
$lang['sys.health_alert_media_failed_message'] = 'Количество media queue items со статусом failed: {count}.';
$lang['sys.health_alert_media_terminal_failed_title'] = 'В очереди медиа есть безвозвратно битые файлы';
$lang['sys.health_alert_media_terminal_failed_message'] = 'Количество media queue items без повторной попытки: {count}.';
$lang['sys.health_alert_media_pending_title'] = 'Фоновая догрузка медиа ещё продолжается';
$lang['sys.health_alert_media_pending_message'] = 'В очереди ещё осталось {count} элементов. Это не ошибка, но импорт ещё не завершён полностью.';
$lang['sys.health_alert_backup_stale_title'] = 'Обнаружены зависшие backup-задачи';
$lang['sys.health_alert_backup_stale_message'] = 'Количество зависших backup jobs: {count}.';
$lang['sys.health_alert_backup_failed_title'] = 'Есть backup-задачи с ошибкой';
$lang['sys.health_alert_backup_failed_message'] = 'Количество backup jobs со статусом failed: {count}.';
$lang['sys.health_alert_mail_transport_title'] = 'Почтовый транспорт недоступен';
$lang['sys.health_alert_mail_transport_message'] = 'Режим почты {mode} настроен без рабочего транспорта ({transport}). Регистрация, восстановление доступа и системные письма будут работать нестабильно.';
$lang['sys.transport'] = 'Транспорт';
$lang['sys.confirm_email_required'] = 'Подтверждение почты';
$lang['sys.media_queue_done'] = 'Готово';
$lang['sys.media_queue_last_completed'] = 'Последняя догрузка';
$lang['sys.media_queue_worker'] = 'Системный агент media-mirror-worker';
$lang['sys.media_queue_worker_notice'] = 'Фоновые медиа автоматически подхватывает встроенный системный агент, созданный при установке.';
$lang['sys.media_queue_worker_save_quick'] = 'Сохранить параметры media-worker';
$lang['sys.media_queue_worker_settings_saved'] = 'Параметры media-worker обновлены.';
$lang['sys.import_media_queue_notification'] = 'Импорт завершён. Медиа поставлены в фоновую очередь системному агенту (%d).';
$lang['sys.refresh_media_metadata'] = 'Обновить метаданные файлов';
$lang['sys.referenced_files'] = 'Связанные файлы';
$lang['sys.unreferenced_files'] = 'Неиспользуемые файлы';
$lang['sys.missing_on_disk'] = 'Отсутствуют на диске';
$lang['sys.dangling_references'] = 'Битые ссылки';
$lang['sys.legacy_payloads'] = 'Legacy payload';
$lang['sys.run_backup'] = 'Создать резервную копию';
$lang['sys.snapshots'] = 'Снапшоты';
$lang['sys.total'] = 'Всего';
$lang['sys.backup'] = 'Резервное копирование';
$lang['sys.backup_job_queued'] = 'Резервная копия поставлена в очередь.';
$lang['sys.backup_job_queue_failed'] = 'Не удалось поставить резервную копию в очередь.';
$lang['sys.backup_jobs_queued'] = 'В очереди';
$lang['sys.backup_jobs_running'] = 'В работе';
$lang['sys.backup_jobs_done'] = 'Готово';
$lang['sys.backup_jobs_partial'] = 'Частично';
$lang['sys.backup_jobs_failed'] = 'С ошибкой';
$lang['sys.backup_scope'] = 'Состав резервной копии';
$lang['sys.backup_scope_project_data'] = 'БД + проектные данные';
$lang['sys.backup_scope_db_only'] = 'Только база данных';
$lang['sys.backup_scope_help'] = 'Проектные данные включают custom/, uploads/, .htaccess и inc/configuration.php. Код фреймворка хранится отдельно в git/релизах.';
$lang['sys.backup_delivery_mode'] = 'Куда отправлять';
$lang['sys.backup_delivery_local_only'] = 'Только локально';
$lang['sys.backup_delivery_local_and_remote'] = 'Локально и на удалённый хост';
$lang['sys.backup_delivery_remote_required'] = 'Удалённый хост обязателен';
$lang['sys.backup_remote_target'] = 'Удалённый хост';
$lang['sys.backup_remote_target_default'] = 'Использовать профиль по умолчанию';
$lang['sys.backup_remote_target_help'] = 'Для удалённой отправки можно выбрать конкретный профиль или использовать профиль по умолчанию.';
$lang['sys.backup_local_storage_notice'] = 'Локальные снапшоты автоматически очищаются по retention-политике.';
$lang['sys.backup_local_snapshots_limit'] = 'последних снапшотов';
$lang['sys.backup_storage_summary'] = 'Локальное хранилище и worker';
$lang['sys.backup_default_remote_target'] = 'Профиль по умолчанию';
$lang['sys.backup_recent_local_snapshots'] = 'Последние локальные снапшоты';
$lang['sys.backup_recent_jobs'] = 'Последние backup-задачи';
$lang['sys.backup_queue_run'] = 'Поставить резервную копию в очередь';
$lang['sys.backup_plans'] = 'Планы резервного копирования';
$lang['sys.backup_plan'] = 'План резервного копирования';
$lang['sys.backup_plan_new'] = 'Новый backup-план';
$lang['sys.backup_plan_edit'] = 'Редактирование backup-плана';
$lang['sys.backup_plan_saved'] = 'План резервного копирования сохранён.';
$lang['sys.backup_plan_deleted'] = 'План резервного копирования удалён.';
$lang['sys.backup_plan_not_found'] = 'План резервного копирования не найден.';
$lang['sys.backup_plan_code'] = 'Код плана';
$lang['sys.backup_plan_default'] = 'План по умолчанию';
$lang['sys.backup_default_plan'] = 'План по умолчанию';
$lang['sys.backup_plan_run_help'] = 'Запуск ставит backup-задачу в очередь. Состав БД, файлов и удалённая отправка берутся из выбранного плана.';
$lang['sys.backup_database_contents'] = 'Состав БД';
$lang['sys.backup_files_contents'] = 'Состав файлов';
$lang['sys.backup_mode_all_tables'] = 'Все таблицы';
$lang['sys.backup_mode_only_selected_tables'] = 'Только выбранные таблицы';
$lang['sys.backup_mode_exclude_selected_tables'] = 'Все таблицы кроме выбранных';
$lang['sys.backup_mode_no_database'] = 'Без базы данных';
$lang['sys.backup_mode_all_files'] = 'Все доступные файлы и папки';
$lang['sys.backup_mode_only_selected_files'] = 'Только выбранные файлы и папки';
$lang['sys.backup_mode_exclude_selected_files'] = 'Все файлы и папки кроме выбранных';
$lang['sys.backup_mode_no_files'] = 'Без файловой части';
$lang['sys.backup_tables_hint'] = 'Список таблиц используется для режимов "только выбранные" и "кроме выбранных".';
$lang['sys.backup_files_hint'] = 'Логи и кэш можно исключать из полного snapshot-плана, а uploads включать или отключать осознанно.';
$lang['sys.backup_tables'] = 'Таблицы БД';
$lang['sys.backup_files_and_folders'] = 'Файлы и папки';
$lang['sys.backup_scheduler_notice'] = 'Резервное копирование работает через фонового системного агента.';
$lang['sys.backup_scheduler_command_help'] = 'На сервере должен быть настроен один минутный scheduler:';
$lang['sys.backup_run_worker_now'] = 'Запустить backup-worker';
$lang['sys.backup_remote_targets'] = 'Удалённые хранилища';
$lang['sys.backup_remote_targets_empty'] = 'Удалённые профили ещё не настроены. Локальные backup-задачи уже работают без них.';
$lang['sys.backup_target_new'] = 'Новый профиль удалённого хранилища';
$lang['sys.backup_target_edit'] = 'Редактирование удалённого хранилища';
$lang['sys.backup_target_not_found'] = 'Профиль удалённого хранилища не найден.';
$lang['sys.backup_target_saved'] = 'Профиль удалённого хранилища сохранён.';
$lang['sys.backup_target_deleted'] = 'Профиль удалённого хранилища удалён.';
$lang['sys.backup_target_default'] = 'По умолчанию';
$lang['sys.backup_target_test'] = 'Проверить подключение';
$lang['sys.backup_target_test_success'] = 'Подключение к удалённому хранилищу подтверждено.';
$lang['sys.backup_target_test_failed'] = 'Не удалось проверить удалённое хранилище.';
$lang['sys.backup_target_code'] = 'Код профиля';
$lang['sys.backup_target_remote_path'] = 'Удалённый путь';
$lang['sys.backup_target_remote_path_help'] = 'Внутри этого пути система создаёт подпапку снапшота и загружает manifest/db/files архивы.';
$lang['sys.backup_target_ftp_passive'] = 'FTP passive mode';
$lang['sys.backup_target_password_keep'] = 'Оставьте пустым, чтобы сохранить текущий';
$lang['sys.host'] = 'Хост';
$lang['sys.port'] = 'Порт';
$lang['sys.login'] = 'Логин';
$lang['sys.timeout'] = 'Таймаут';
$lang['sys.cron_handler_backup_worker'] = 'Фоновая обработка резервных копий';
$lang['sys.cron_handler_backup_worker_desc'] = 'Подхватывает queued backup-задачи, создаёт локальные снапшоты и отправляет их на удалённые хосты.';
$lang['sys.cron_agent_payload_backup_stale_after'] = 'Считать зависшей через, сек';
$lang['sys.cron_agent_payload_backup_stale_after_help'] = 'Если backup-задача слишком долго висит в running, worker переведёт её в failed и освободит очередь.';
$lang['sys.fill_with_test_data'] = 'Заполнить тестовыми данными';
$lang['sys.delete_database_data'] = 'Удалить данные БД';
$lang['sys.project_development'] = 'Развитие проекта';
$lang['sys.order_a_project'] = 'Заказать проект';
$lang['sys.review'] = 'Обзор';
$lang['sys.dashboard_overview_heading'] = 'Обзор проекта';
$lang['sys.dashboard_overview_subtitle'] = 'Живой срез каталога, импорта, агентов и операционного состояния.';
$lang['sys.dashboard_operational_alerts'] = 'Операционные сигналы';
$lang['sys.dashboard_content_quality'] = 'Контентная готовность';
$lang['sys.dashboard_readiness_percent'] = 'Готово к публикации';
$lang['sys.dashboard_pages_active'] = 'Активных';
$lang['sys.dashboard_pages_hidden'] = 'Скрытых';
$lang['sys.dashboard_categories_with_photos'] = 'С галереей';
$lang['sys.dashboard_categories_with_map'] = 'С картой';
$lang['sys.dashboard_owner_links'] = 'Связано владельцев';
$lang['sys.dashboard_pages_without_owner'] = 'Без владельца';
$lang['sys.dashboard_pages_without_contacts'] = 'Без контактов';
$lang['sys.dashboard_pages_without_photos'] = 'Без фото';
$lang['sys.dashboard_pages_without_rooms'] = 'Без блока номеров';
$lang['sys.dashboard_contacts_verified'] = 'Контакты проверены';
$lang['sys.dashboard_paid_placements'] = 'Платное размещение';
$lang['sys.dashboard_placements_expiring'] = 'Истекает в 30 дней';
$lang['sys.dashboard_recent_imports'] = 'Последние импорты';
$lang['sys.dashboard_recent_agent_runs'] = 'Последние запуски агентов';
$lang['sys.dashboard_recent_backups'] = 'Последние backup-задачи';
$lang['sys.dashboard_no_imports'] = 'Профили импорта ещё не запускались.';
$lang['sys.dashboard_no_runs'] = 'Запусков агентов пока нет.';
$lang['sys.dashboard_no_backup_jobs'] = 'Backup-задачи ещё не запускались.';
$lang['sys.dashboard_admin_only'] = 'Подробный обзор системы доступен администратору.';
$lang['sys.dashboard_contacts_block'] = 'Контакты и фото';
$lang['sys.dashboard_room_block'] = 'Номера и размещение';
$lang['sys.kill_db'] = 'Все таблицы БД будут удалены!';
$lang['sys.error_type'] = 'Тип ошибки';
$lang['sys.stack_trace'] = 'Трассировки стека';
$lang['sys.log_channel'] = 'Канал';
$lang['sys.log_channels'] = 'Каналов';
$lang['sys.file_count'] = 'Файлов';
$lang['sys.archive_count'] = 'Архивов';
$lang['sys.log_size'] = 'Размер';
$lang['sys.last_update'] = 'Последнее обновление';
$lang['sys.level'] = 'Уровень';
$lang['sys.request_id'] = 'Request ID';
$lang['sys.request'] = 'Запрос';
$lang['sys.context'] = 'Контекст';
$lang['sys.meta'] = 'Мета';
$lang['sys.initiator'] = 'Инициатор';
$lang['sys.result'] = 'Результат';
$lang['sys.details'] = 'Детали';
$lang['sys.subscribed'] = 'Подписан';
$lang['sys.required_consents'] = 'Обязательные согласия';
$lang['sys.required_consents_title'] = 'Обязательные документы';
$lang['sys.required_consents_intro'] = 'Для продолжения работы с платформой примите два обязательных документа.';
$lang['sys.required_consents_missing'] = 'Для продолжения необходимо принять Политику и Согласие на обработку персональных данных.';
$lang['sys.privacy_policy'] = 'Политика в отношении обработки персональных данных';
$lang['sys.personal_data_consent'] = 'Согласие на обработку персональных данных';
$lang['sys.accept_privacy_policy'] = 'Я ознакомлен(а) и принимаю Политику в отношении обработки персональных данных';
$lang['sys.accept_personal_data_consent'] = 'Я даю согласие на обработку персональных данных';
$lang['sys.privacy_policy_acceptance_required'] = 'Необходимо принять Политику в отношении обработки персональных данных.';
$lang['sys.personal_data_consent_required'] = 'Необходимо дать согласие на обработку персональных данных.';
$lang['sys.save_consents'] = 'Сохранить согласия';
$lang['sys.open_document'] = 'Открыть документ';
$lang['sys.document_version'] = 'Версия документа';
$lang['sys.accepted_at'] = 'Принято';
$lang['sys.provider_consent_title'] = 'Подтверждение обязательных документов';
$lang['sys.provider_consent_intro'] = 'Перед продолжением через внешний провайдер подтвердите обязательные документы платформы.';
$lang['sys.continue'] = 'Продолжить';
$lang['sys.filtres'] = 'Фильтры';
$lang['sys.database'] = 'База данных';
$lang['sys.copy'] = 'Копировать';
$lang['sys.insert'] = 'Вставить';
$lang['sys.cancel'] = 'Отмена';
$lang['sys.close'] = 'Закрыть';
$lang['sys.download'] = 'Загрузить';
$lang['sys.authorization'] = 'Авторизация';
$lang['sys.continue_with_google'] = 'Продолжить через Google';
$lang['sys.provider_not_configured'] = 'Вход через выбранного провайдера пока не настроен.';
$lang['sys.provider_profile_incomplete'] = 'Провайдер не вернул обязательные данные профиля.';
$lang['sys.provider_state_invalid'] = 'Сессия внешней авторизации истекла или недействительна.';
$lang['sys.provider_auth_failed'] = 'Ошибка внешней авторизации. Попробуйте ещё раз.';
$lang['sys.account_link_email_sent'] = 'Мы отправили письмо для подтверждения привязки внешнего аккаунта.';
$lang['sys.account_link_completed'] = 'Внешний аккаунт успешно привязан.';
$lang['sys.imports_property_definitions'] = 'JSON: типы/свойства/наборы';
$lang['sys.import_source_property_map'] = 'Прямое сопоставление свойств';
$lang['sys.import_source_property_map_help'] = 'Используйте по одной строке: source_property_id = локальное имя свойства или source_property_id = #123. Это нужно для прямого импорта WP meta в уже созданные curated-свойства EE.';
$lang['sys.imports_stage_1_label'] = 'Запустить этап 1';
$lang['sys.imports_stage_1_running'] = 'Этап 1 выполняется...';
$lang['sys.imports_stage_1_done'] = 'Этап 1 завершён';
$lang['sys.imports_stage_1_error'] = 'Ошибка этапа 1';
$lang['sys.imports_stage_2_label'] = 'Запустить этап 2';
$lang['sys.imports_stage_2_running'] = 'Этап 2 выполняется...';
$lang['sys.imports_stage_2_done'] = 'Этап 2 завершён';
$lang['sys.imports_stage_2_error'] = 'Ошибка этапа 2';
$lang['sys.imports_full_label'] = 'Запустить все фазы';
$lang['sys.imports_full_running'] = 'Полный импорт выполняется...';
$lang['sys.imports_full_done'] = 'Полный импорт завершён';
$lang['sys.imports_full_error'] = 'Ошибка полного импорта';
$lang['sys.tools'] = 'Инструменты';
$lang['sys.email_templates'] = 'Почтовые шаблоны';
$lang['sys.system'] = 'Система';
$lang['sys.snippets'] = 'Сниппеты';
$lang['sys.vars'] = 'Переменные';
$lang['sys.archive'] = 'Архив';
$lang['sys.theme'] = 'Тема';
$lang['sys.back'] = 'Назад';
$lang['sys.add_email_template'] = 'Добавить шаблон письма';
$lang['sys.edit_email_template'] = 'Редактировать шаблон письма';
$lang['sys.enter_name'] = 'Введите название';
$lang['sys.subject'] = 'Тема';
$lang['sys.enter_subject'] = 'Введите тему';
$lang['sys.enter_description'] = 'Введите описание';
$lang['sys.body'] = 'Тело';
$lang['sys.enter_body'] = 'Введите тело';
$lang['sys.preview'] = 'Предварительный просмотр';
$lang['sys.error'] = 'Ошибка';
$lang['sys.removed'] = 'Удалено';
$lang['sys.require_password_setup'] = 'Требовать назначить новый пароль';
$lang['sys.ip_restricted'] = 'Ограничить авторизацию по IP';
$lang['sys.local_password'] = 'Локальный пароль';
$lang['sys.failed_attempts'] = 'Неудачные попытки';
$lang['sys.locked_until'] = 'Блокировка до';
$lang['sys.linked_providers'] = 'Связанные провайдеры';
$lang['sys.no_linked_providers'] = 'Связанных внешних провайдеров пока нет.';
$lang['sys.restore_user'] = 'Восстановить пользователя';
$lang['sys.restore_user_confirm'] = 'Восстановить пользователя и потребовать назначить новый пароль?';
$lang['sys.user_restored'] = 'Пользователь восстановлен.';
$lang['sys.single_admin_only'] = 'В системе может быть только один администратор.';
$lang['sys.single_admin_demotion_forbidden'] = 'Нельзя снять роль у единственного администратора.';
$lang['sys.language'] = 'Язык';
$lang['sys.content_language'] = 'Язык содержимого';
$lang['sys.language_switch_help'] = 'Переключение обновляет форму и связанные списки в выбранной локали.';
$lang['sys.translations'] = 'Переводы';
$lang['sys.translation_source'] = 'Исходная версия';
$lang['sys.translation_draft_help'] = 'Создаётся новый перевод на основе выбранной исходной версии.';
$lang['sys.translation_list_help'] = 'Список показывает записи в выбранной локали интерфейса. Существующие переводы можно открыть прямо из таблицы.';
$lang['sys.category_edit'] = 'Редактирование категории';
$lang['sys.category_add'] = 'Добавление категории';
$lang['search.title'] = 'Поиск по панели управления';
$lang['search.breadcrumb_results'] = 'Результаты поиска';
$lang['search.you_searched_for'] = 'Вы искали';
$lang['search.results_found'] = 'Найдено результатов';
$lang['search.results_list_title'] = 'Список найденных материалов';
$lang['search.result_relevance'] = 'Релевантность';
$lang['search.no_results_found'] = 'По вашему запросу ничего не найдено. Попробуйте изменить формулировку.';
$lang['search.enter_query'] = 'Введите поисковый запрос в форму вверху страницы.';
return $lang;
